### PR TITLE
list: allow trait objects as list items

### PR DESCRIPTION
**Pull request by daniel-scs**
### Pull Request Overview

The library in `kernel::common::list` provides a linked-list implementation, but the interface unnecessarily prevents constructing a list of trait objects.

This PR relaxes the relevant type signatures to allow this.

### Testing Strategy

Although the fix to `list.rs` is simple, actually using the list library to put together this kind of list is a bit hairy and requires specifying a lot of lifetimes correctly.  To aid developers, this PR includes an example in `capsules::examples::traitobj_list`.

### TODO or Help Wanted

Ready for merge.

### Documentation Updated

- [x] Kernel: The relevant files in `/docs` have been updated or no updates are required.
- [x] Userland: The application README has been added, updated, or no updates are required.

### Formatting

- [x] `make formatall` has been run.

(I'm having trouble with the formatting tools at the moment.)

### CODE REVIEW

**Comment by alevy** [comment]
It might be worth adding a top-level `examples` folder which can be compiled separately http://doc.crates.io/guide.html#project-layout

Otherwise I think this is good, modulo the formatting. Though, I don't really understand what `?Sized` does...

**Comment by daniel-scs** [comment]
Do you mean the examples folder should be another top-level crate?  And then I guess one could run example code by temporarily adding `extern crate examples` to a board?

As for `?Sized`, this just allows the list-item type, `T`, be something that doesn't have known size at compile time, like a trait object.

**Comment by brghena** [comment]
Based on the link, I thought the idea was to have a `capsules/examples` folder and place the code in there (rather than in `capsules/src`). I'm not sure how you'd include it in a board in that case though.

**Comment by daniel-scs** [comment]
Hm thanks, but this PR already does that -- the example is in `capsules/examples`.

Certainly it would be nice to not have to compile example/test code when not needed, but I would like to make sure it does compile.  Can we rely on LTO not linking in something like this if it doesn't get used?

**Comment by alevy** [comment]
> Can we rely on LTO not linking in something like this if it doesn't get used?

yes, it'll just still increase the compilation time of the crate itself, is all. probably not a huge deal. But if the examples are not in `src`, I don't think they'll get compiled with the `--examples` argument

**Comment by alevy** [comment]
> the example is in capsules/examples

perhaps there is a missing commit or something? the current PR shows the new files in `capsules/src/examples`

**Comment by bradjc** [comment]
Does this look good now?

**Comment by daniel-scs** [comment]
Sorry, I was confused.  Thanks Brad!

**Comment by alevy** [comment]
I see basically zero harm in adding this (negative) constraint, and now that the example is in The Right Place(tm) I'll merge unless someone protests soon.

**Pull request merged**
