### PR TITLE
Changes NRF UART from ptrs to volatile cells

### PR DESCRIPTION
**Pull request by amilich**
ptr::write_volatile and read_volatile no longer used in uart.rs; each register is now a VolatileCell.

### CODE REVIEW

**Comment by alevy** [comment]
There are some formatting issues (which is why the build failed). You can fix them by running:

```bash
$ find -path ./userland -prune -o -name '*.rs' -exec rustfmt {} +
```

from the root directory

**Comment by alevy** [comment]
Can you put the `send_bytes` commit in a separate pull request after we merge this one? There are some issues with it, but other than formatting we ought to be able to just merge the original request.

**Comment by alevy** [comment]
@amilich the only issue is formatting, which, when I fetch your code locally, was fixed with:

```
$ find -path ./userland -prune -o -name '*.rs' -exec rustfmt {} +
```

**Comment by amilich** [comment]
I'll try running that again from tock root and see if I see changes.

**Comment by alevy** [comment]
BTW, in master and thanks to @bradjc, we now have `make fmt` (#132) which basically does this for you, so should be easier from now on.

**Comment by alevy** [comment]
Still a extraneous newline, but I'm just going to merge and fix it manually

**Pull request merged**
