### PR TITLE
Process lib - clone_from_slice stable

### PR DESCRIPTION
**Pull request by 0xc0170**
Just one warning elimination. I am currently on rustc-7dce32e65 nightly

### CODE REVIEW

**Comment by ppannuto** [comment]
We need to be a little more careful about stuff like this, the readme currently says:

    We are using `rustc 1.7.0-nightly (110df043b 2015-12-13)`.

And this patch breaks compilation for that version of rust.

```
$ rustc --version
rustc 1.7.0-nightly (110df043b 2015-12-13)
$ make
Building build/libprocess.rlib
/Volumes/code/helena-project/tock/src/process/process.rs:143:21: 143:48 error: use of unstable library feature 'clone_from_slice' (see issue #27750)
/Volumes/code/helena-project/tock/src/process/process.rs:143         target_data.clone_from_slice(init_data);
                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/code/helena-project/tock/src/process/process.rs:143:21: 143:48 help: add #![feature(clone_from_slice)] to the crate attributes to enable
error: aborting due to previous error
make: *** [build/libprocess.rlib] Error 101
```

Updating rust does resolve the issue.

Perhaps while things are moving quickly, we should have the Makefile check rust version and fail out (or run multirust) if it doesn't match?

**Comment by ppannuto** [comment]
@0xc0170 , I wanted to give you a heads up that we've reverted this change for now. It's too hard to support multiple versions of rust at once. We will periodically bump rust versions as new features merit, but otherwise we try to stay on one version to minimize churn. We'll re-apply this whenever we next update rust.

I've added a check to the Makefile that enforces this to help avoid confusion in the future.

**Comment by 0xc0170** [comment]
> We need to be a little more careful about stuff like this, the readme currently says:

@ppannuto I specified the rust I compilied above. I am aware of the readme version, but as it is nightly, I assumed we could update (as it was one week difference between versions)

> I wanted to give you a heads up that we've reverted this change for now.
Fine with revert, I'll downgrade my rust for now then.

 How often do you update to newer nightly? Who is in charge to upgrade this if I can't . Does that happen periodically in some period?

**Comment by ppannuto** [comment]
I was surprised to have the issue as well, and thanks for specifying your
version, made testing really easy.

I don't think we have a formal schedule for updating rust versions. It is
probably something that was should put into place, however my personal
inclination is to largely avoid updating rust versions unless (1) something
is added that we need, or (2) something is changed that may affect our
project -- (2) is admittedly a little harder stay on top of. I feel like
there are enough moving parts here that changing rust versions is another
variable we don't ned to introduce if we can help it.

As our foremost rust expert, I imagine @alevy will be in charge of this.
I'll bring it up with him tomorrow.

**Comment by 0xc0170** [comment]
I understand, and will follow for this project the version in Readme. thanks for clarification.

**Comment by phil-levis** [comment]
I agree on the Rust version; tracking a quickly moving compiler is a huge pain. We should move forward on compiler versions on the above conditions or approximately every 6 months or so.

**Comment by alevy** [comment]
I agree on tracking the compiler version.

There is only one feature that, when it lands in Rust, we ought to switch versions for: a `const fn` version of `size_of`. It's waiting on better support from the mid-level IR. When we have that we can size static buffers automatically at compile time (right now, we just use some large number, like 1024).

**Pull request merged**
