### PR TITLE
Prevent auto-format when using VSCode

### PR DESCRIPTION
**Pull request by Woyten**
### Pull Request Overview

Hi, I'm working with Tock using VSCode with global `formatOnSave` enabled and I am probably not the only one. In order to disable the formatting for Tock, I need to set a local VSCode option in the Tock workspace. Unfortunately, this setting is recognized as an untracked file in git.

My proposed solution is to check in the VSCode settings file into the repository. As an alternative we could also ignore the whole `.vscode` folder in `.gitignore`. Still, I prefer the first solution s.t. every Tock developer will work with `formatOnSave` disabled.

Cheers,
Woyten

### CODE REVIEW

**Comment by alevy** [comment]
Thanks!

Could you explain why it's beneficial to disable formatOnSave when working on Tock?

**Comment by Woyten** [comment]
Hi,

actually, it's not really beneficial to disable it. ;-) Au contraire, I would strongly prefer to have such a mechanism in place.

However, my observation is that whenever I save a Tock file with `formatOnSave` I get a lot of diff noise. My explanation is that (at least to my understanding) we use `make formatall` to format the source code which does not produce the same results as `formatOnSave` by VSCode.

Do you have any explanation why this is the case? It would be great if this could be fixed somehow.

**Comment by alevy** [comment]
Hrm... formatall just uses rustfnt, but I think with particular options and potentially a different version than what vscode uses. Perhaps either upgrading which rustfmt we use or tweaking the arguments VSCode uses might do the trick?

**Comment by Woyten** [comment]
Yes, the versions seem to be different and, to make it more complicated, there is `rustfmt` and `rustfmt-nightly`. I think one step of the solution is to set the local `rust-client.channel` option to `nightly-2017-11-19`. I will check this option.

**Comment by ppannuto** [comment]
Indeed, we pegged to rustfmt v0.7.1 a long time ago when rustfmt was changing somewhat rapidly and creating a lot of uninteresting churn.

It's probably time to bump to a newer rustfmt (with all the associated noise.. :/ ) -- I _think_ moving forward we can tie rustfmt versions to rustc versions and bump them together, which is probably reasonable. I'll look into this.

**Comment by Woyten** [comment]
Thank @ppannuto for your work! If we switch to the most recent `rustfmt` we could default `formatOnSave` to true for VSCode users. We should also force a specific RLS version on VSCode, s.t. the RLS picks the correct `rustfmt` version. I updated the PR accordingly.

**Comment by alevy** [comment]
OK, @ppannuto can you just merge this, then, when #720 is done?

**Pull request merged**
