### PR TITLE
Add last syscall fired to app debug printout

### PR DESCRIPTION
**Pull request by ppannuto**
---| App Status |---
    App: hail   -   [Yielded]
     Events Queued: 0   Syscall Count: 9   Last Syscall: Some(YIELD)

I did this by converting syscall from a const to an enum, which I
think makes sense in general as well, but maybe not

### CODE REVIEW

**Comment by brghena** [comment]
Super cool.

One small change would be unwrapping before it is printed so that only "YIELD" is printed rather than "Some(YIELD)"

**Comment by ppannuto** [comment]
Yeah I suspected someone would comment on that, what's the right way to do that and handle None? (Given that I'd like it to print None if there's never been a syscall). I'd hoped the debug formatter would just do it for me, but I suppose it makes sense that it prints the fact that it's an option

**Comment by alevy** [comment]
@ppannuto it's not super pretty. An easy thing might be to just separate the call to `write_fmt` into three separate ones and have the middle one be dependent on `last_syscall`, so something like:

```rust
let _ =match last_syscall {
    Some(syscall) => writer.write_fmt(format_args!("Last Syscall: {?}", syscall)),
    None => write.write_fmt(format_args!("Last Syscall: None"))
}
```

**Comment by bradjc** [comment]
Maybe you could make a string like how "EXCEEDED" works?

**Comment by ppannuto** [comment]
@bradjc one of the reasons for turning this into an enum is so that the compiler would do that for me. I could've written that same match statement with the numbers they used to be

Inspired by `impl<'a> Write for &'a mut [u8]`, I tried getting cute and doing something like this:

```rust
static mut last_syscall_str: &'static mut [u8; 12] = &mut [0; 12];
```

but that gets

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C boards/storm/
   Compiling kernel v0.1.0 (file:///private/tmp/tock/kernel)
<core macros>:2:8: 2:18 error: no method named `write_fmt` found for type `&'static mut [u8]` in the current scope
<core macros>:2 $ dst . write_fmt ( format_args ! ( $ ( $ arg ) * ) ) )
                       ^~~~~~~~~~
/private/tmp/tock/kernel/src/process.rs:881:34: 881:80 note: in this expansion of write! (defined in <core macros>)
<core macros>:2:8: 2:18 note: the method `write_fmt` exists but the following trait bounds were not satisfied: `[u8] : core::fmt::Write`
```

Which is I _believe_ is telling me that my primitive slice doesn't have the Write trait implemented (despite there already being a `use core::fmt::Write` at the top of the file, which I thought would pull that in)

That led me down the blind alley of trying to mirror this from Read http://stackoverflow.com/questions/37881254/create-read-trait-object-from-u8-slice

which seems to be a means of casting a trait onto a slice? I dunno, no combination of things ended up working for me, the last thing I had before throwing in the towel was:

```rust
static mut last_syscall_str_arr: mut [u8; 12] = &mut [0; 12];
//static mut last_syscall_str_slice: &'static mut [u8] = last_syscall_str_arr;  // need to drop this intermediate b/c trait requires Sized (needs to know how long array is) and this loses that; that make sense at least
static mut last_syscall_str: &'static mut Write = last_syscall_str_arr;
```

Which somehow led to the bound trait issue all over again

```rust
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C boards/storm/
   Compiling kernel v0.1.0 (file:///private/tmp/tock/kernel)
/private/tmp/tock/kernel/src/process.rs:250:51: 250:71 error: the trait bound `[u8; 12]: core::fmt::Write` is not satisfied [E0277]
/private/tmp/tock/kernel/src/process.rs:250 static mut last_syscall_str: &'static mut Write = last_syscall_str_arr;
                                                                                              ^~~~~~~~~~~~~~~~~~~~
/private/tmp/tock/kernel/src/process.rs:250:51: 250:71 help: run `rustc --explain E0277` to see a detailed explanation
/private/tmp/tock/kernel/src/process.rs:250:51: 250:71 note: required for the cast to the object type `core::fmt::Write + 'static`
```

I'm willing to give up and go to a different implementation, but I was hoping that @alevy (or anyone else) could explain what the heck is going on with this bound trait nonsense?

(Amusingly and/or revealingly, one of the top results for the bound traits error is this github issue which observes that that's an unhelpful diagnostic https://github.com/rust-lang/rust/issues/36513)

**Comment by brghena** [comment]
@ppannuto What did this PR actually change? Was it only the Syscall type and the printing in `process.rs`? Unfortunately due to the rustfmt it shows you touched 36 files...

**Comment by ppannuto** [comment]
It's just the original PR + amit's suggested change. You should be able to
click on the individual commit objects to see the files

**Pull request merged**
