### PR TITLE
sam4l: dma: update to new regs interface

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates the SAM4L DMA peripheral to the new register interface.

### Testing Strategy

This pull request needs to be tested.

### TODO or Help Wanted

This pull request doesn't compile because of the `DMAPeripheral` enum. It was handled nicely before (although I'm not sure why rust didn't complain) and I'm not sure how to replicate that in new register interface land.

### Documentation Updated

- [x] Kernel: Updated the relevant files in `/docs`, or no updates are required.
- [x] Userland: Added/updated the application README, if needed.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
Hmm, this may be exposing an ergonomics bit that's kinda rough. The problem was the you've changed the type of the `psr` register. However, once you make the `psr` a `DMAPeripheral`, then the registers interface requires that `DMAPeripheral` be "`IntLike`". Not so bad for things like `Eq` where you can just derive, but there's not derives for `BitAnd`, `BitOr`, `Not`, `Shr`, or `Shl`, so now you're writing a lot of code. This is the start of the needed fix:

```diff
diff --git a/chips/sam4l/src/dma.rs b/chips/sam4l/src/dma.rs
index 3c94bb8b..26918776 100644
--- a/chips/sam4l/src/dma.rs
+++ b/chips/sam4l/src/dma.rs
@@ -2,7 +2,8 @@

 use core::{cmp, intrinsics};
 use core::cell::Cell;
-use kernel::common::regs::{ReadOnly, ReadWrite, WriteOnly};
+use core::ops::BitAnd;
+use kernel::common::regs::{IntLike, ReadOnly, ReadWrite, WriteOnly};
 use kernel::common::take_cell::TakeCell;
 use pm;

@@ -11,7 +12,7 @@ use pm;
 #[allow(dead_code)]
 struct DMARegisters {
     mar: ReadWrite<u32, MemoryAddress::Register>,
-    psr: ReadWrite<u32, PeripheralSelect::Register>,
+    psr: ReadWrite<DMAPeripheral, PeripheralSelect::Register>,
     tcr: ReadWrite<u32, TransferCounter::Register>,
     marr: ReadWrite<u32, MemoryAddressReload::Register>,
     tcrr: ReadWrite<u32, TransferCounter::Register>,
@@ -124,7 +125,7 @@ pub enum DMAChannelNum {
 /// means transfer data from peripheral to memory, `*_TX` means transfer data
 /// from memory to peripheral.
 #[allow(non_camel_case_types)]
-#[derive(Copy, Clone, PartialEq)]
+#[derive(Copy, Clone, Eq, PartialEq)]
 #[repr(u8)]
 pub enum DMAPeripheral {
     USART0_RX = 0,
@@ -167,6 +168,20 @@ pub enum DMAPeripheral {
     LCDCA_ABMDR_TX = 38,
 }

+impl IntLike for DMAPeripheral {
+    fn zero() -> Self {
+        0
+    }
+}
+
+impl BitAnd for DMAPeripheral {
+    type Output = Self;
+
+    fn bitand(self, rhs: Self) -> Self {
+        self.0 & rhs.0
+    }
+}
+
 #[derive(Copy, Clone, Debug, PartialEq)]
 #[repr(u8)]
 pub enum DMAWidth {
```

**Comment by alevy** [comment]
It is ok for _some_ stuff not to use the register interface

**Comment by ppannuto** [comment]
Yes and no. If there's something the register interface doesn't handle well, maybe we just need to fix the register interface.

It would be nice to be able to automatically derive `IntLike` for enum types that are effectively `u32`s.  This could be fixed by just throwing away the `DMAPeripheral` type an using a `u32` in its place, but that's pretty antithetical to our goals.

It may be that the solution here is just to author our own derive for "int-like" enums. Or maybe there's already something in Rust proper that we could use to do that for us. We can't be the first people who want to have int-like enums...

**Comment by bradjc** [comment]
Taking Pat's example a little further, the next problem is that to do the operations (like bitwise and) you have to convert the `DmaPeripheral` enum to a u32 (or something) to do the operation, but then turning it back into a `DmaPeripheral` is difficult (I think). This gets back to why I wasn't sure why rust would even let us do this in the first place because a u8 can have 256 values yet our enum only defined 39.

**Comment by bradjc** [comment]
OK I think this version works now. It does change the channel back to a `VolatileCell`. The reasons is that for `IntLike` you have to implement `Not`. For that to work you are (likely) going to end up with a value that is not a valid enum, yet the `Not` function has to return a enum. To make that work correctly I ended up defining all values of the enum, which is...not great. My work is here: https://github.com/helena-project/tock/compare/sam4l-new-regs-dma-full?expand=1

All things considered this solution is fine. I might be missing something which would make the enums work, but I'm happy with just leaving one `VolatileCell`.

**Pull request merged**
