### PR TITLE
attempt to make generic interfaces for humidity and temperature sensors

### PR DESCRIPTION
**Pull request by niklasad1**
Hi,

This is an attempt to solve [#444](https://github.com/helena-project/tock/issues/444)
For discussion on the design please see  [#444](https://github.com/helena-project/tock/issues/444)

The structure of the "generic" temperature and humidity capsules are more or less "copy-paste" from the ninedof capsule.

However, there exist one bug in the overall structure once an invalid command arrives the "busy" flag will never be cleared because a callback will never be fired. But I have not solved that in this PR. I have not verified if this is the case for [ninedof.rs](https://github.com/helena-project/tock/blob/master/capsules/src/ninedof.rs) and [ambient_light.rs](https://github.com/helena-project/tock/blob/master/capsules/src/ambient_light.rs)

I have modified the actual the implementation of [si7021.rs](https://github.com/helena-project/tock/blob/master/capsules/src/si7021.rs) as a ```test subject```.  There exist some degree of boiler plate code but I wanted it to implement two different interfaces namely temperature and humidity. The previous implementation combined them.

Also I made the internal temperature sensor of nRF51 to comply with the new interface.

Futhermore, I have added two new libraries in libtock:

- temperature.[h/c]
- humidity.[h/c]

Those are very similar to si7021.[c/h]

Lastly I have modified the [sensors app](https://github.com/helena-project/tock/blob/master/userland/examples/sensors/) where si7021 are replaced by temperature and humdity through the "new" interface.

This is implementation will assume that there will only exist one command number for temperature and other sensors etc. Once several sensors exist the interface should be extended to combine several sensors for more accurate measurements.

Thoughts?

### CODE REVIEW

**Comment by alevy** [comment]
@niklasad1 I made some pretty significant changes to the interface, though very few to the actual implementation.

Sorry to step on your branch, but this is actually urgent enough that I figured it's OK just this one time. I also tried to put make the commits such that it should be relatively easy to revert individually if you disagree.

Can you take a look and merge if you're happy or fix or comment if you're unhappy?

In no particular order:

  1. I removed the differentiation between ambient and CPU temperature in the interface itself. the interfaces are identical, and I doubt that any one hardware implementation will ever implement both. To the extent there is differentiation, it should be in the driver number, but that can be resolved in #559.

  2. I fixed an important multiplexing bug in the SI7021. As it was, if you tried to read the humidity and temperature concurrently, one would just get lost. This is a problem because they are different drivers, so the user has no way of knowing they shouldn't that (indeed if they are implemented with different chips it should be fine). The implementation is fairly straight forward though.

  3.  I removed the `ReturnCode` from the temperature and humidity callbacks. This conforms better to what ninedof and ambient light do and it wasn't actually being used. I'm not against having that argument to future proof the interface if we can come up with a scenario where it would be useful, but for now, I thought consistency is more important (and if we add it to one, we should add it to all).

  4. I merged the sensor HILs into one module and pluralized it.

  5. Some other cosmetic stuff

**Comment by niklasad1** [comment]
@alevy 

1. Ok, I have no strong opinion on that
2. Good, solved my concern
3. For now it makes sense at least i.e. as you said they are unused but perhaps we could have it in mind for further improvements e.g. if the the i2c bus fails or some other scenario that I can't come up with now :)
4. Very good, well I thought you would never agree with that because we now have different capsules for the sensors and one HIL. Nevertheless, I think this makes sense because each sensor interface is only a few lines of code and a separate file feels like overkill!
5. good

Looks good to me for a merge but can you double check if the [example sensor app](https://github.com/niklasad1/tock/blob/capsule/generic_temp_sensor/userland/examples/sensors/main.c) is ok?

**Comment by alevy** [comment]
The sensors app works right for me...

**Comment by niklasad1** [comment]
Yes but before the temperature readouts was named ```(si7021) temperature xx deg C``` and ```(si7021) humidity xx%``` and now only ```temperature xx deg C``` and ```humidity xx%``` that was my only concern!

**Comment by alevy** [comment]
Oh that was on purpose since it's technically more general now

**Pull request merged**
