### PR TITLE
Add missing sentinel at the end of .apps section for sam4l

### PR DESCRIPTION
**Pull request by Grawp**
and also fix indentation in nrf51 linker script.

### CODE REVIEW

**Comment by alevy** [comment]
I suspect we probably want this, but want to see if other folks working with the SAM4L agree (@bradjc, @ppannuto, @brghena, @nealjack).

It would basically mean that when you re-program/flash the kernel, it always invalidates whatever apps were previously programmed there (since it overwrites the first word of the first app with a sentinel).

**Comment by alevy** [comment]
Note: this hasn't generally come up as an issue on fresh the Firestorm because @immesys has been giving them to us with the flash zeroed out, but I did run into this with Imix's SAM4L which comes "erased", i.e., all 1's.

**Comment by Grawp** [comment]
I actually do not have the Firestorm board. I'm currently trying to port Tock to stm32f4discovery board. I've used (just a little modified) linker-script from sam4l and found out that it is missing the sentinel while stepping the process loading in a debugger.
Unless sam4l is using a very different flashing procedure from stm32f4, I thing this is an issue for sam4l as well, but of course I can be easily mistaken (not knowing sam4l enough).

**Comment by alevy** [comment]
@Grawp yes this 100% makes sense and as you've clearly noticed, it's what we do for the nrf51. I just want to give the people I mentioned a chance to raise concerns.

**Comment by ppannuto** [comment]
We chatted about this briefly, but I think we'd call this an anti-feature.

When fixing kernel issues, it's really nice to not have to re-flash your test app.

That said, we've also talked about having a checksum or other validation of an app header to prevent errors in the missing-app case. I think that'd be a better approach.

**Comment by alevy** [comment]
@ppannuto How about starting with a header word at the beginning of each binary. It's not the full solution (checksums make sense), but it would solve at least the current problem and is easy to implement.

How about 0x7bfa99? ("tbfapp" lookalike)

**Comment by ppannuto** [comment]
Yeah, that sounds like a plan to me.

**Comment by alevy** [comment]
@Grawp is this something you're interested in doing? I can help point you to how, it shouldn't be too bad.

There are basically two data structures that model the header, called `LoadInfo`:

  1. [kernel/src/process.rs#60](https://github.com/helena-project/tock/blob/master/kernel/src/process.rs#L60)

  2. [userland/tools/elf2tbf/src/main.rs#17](https://github.com/helena-project/tock/blob/master/userland/tools/elf2tbf/src/main.rs#L17)

It should be just a matter of extending those structs with an expected word at the very beginning, then checking for that word in `load_processes`.

**Comment by Grawp** [comment]
@alevy Yes I'm certainly interested but first I have to get the stm32f4 port to a state where I can have stdout from processes. I hopefully will have some time to do it in a next few days.

**Comment by alevy** [comment]
@Grawp feel free to ask for help if you run into issues on the [mailing list](https://groups.google.com/forum/#!forum/tock-dev)

**Pull request closed without merging**
