### PR TITLE
Remove incorrect `naked` attributes

### PR DESCRIPTION
**Pull request by ppannuto**

### CODE REVIEW

**Comment by alevy** [comment]
Um... Explanation? Those were there pretty intentionally. If there was a bug could you please explain it?

**Comment by ppannuto** [comment]
Quoting from the first commit:

> Remove incorrect `naked` attributes  …
> TIL that the `naked` attribute can only be used for functions that
> contain only "Basic Asm", i.e. asm directives without any clobbers
> or memory references. `naked` functions also can't contain any C
> code.
> 
> Ran into some funny business around this while futzing with LTO
> 
> https://gcc.gnu.org/onlinedocs/gcc/ARM-Function-Attributes.html#ARM-Function-Attributes
> https://gcc.gnu.org/onlinedocs/gcc/Basic-Asm.html#Basic-Asm

If you turn on link-time optimization (which I'm currently playing with adding to further reduce binary sizes), you get this error `error: local frame unavailable (naked function?)` for the functions that were incorrectly marked as naked.

I did validate that after this change, the assembly is what I expected:

```asm
800000c4 <subscribe>:
800000c4:       df01            svc     1
800000c6:       4770            bx      lr
```

and that several applications work correctly on hardware.

**Comment by ppannuto** [comment]
It's also worth highlighting this quote from the gcc doc's:

> While using extended asm or a mixture of basic asm and C code may appear to work, they cannot be depended upon to work reliably and are not supported. 

Which likely explains why we weren't burned before.

**Comment by alevy** [comment]
OK... that's a bummer (cause it adds a bunch of unnecessary instructions) but I understand.

**Comment by ppannuto** [comment]
It shouldn't be adding any unnecessary instructions. My understanding is that `naked` only affects the callee, not the caller, and the compiler can analyze the callee function here and see that it only uses caller-saved registers (r0-r3), and therefore it doesn't need emit any prologue/epilogue sequences. Indeed, the two apps that I looked at the assembly for it does this correctly and doesn't add any unnecessary instructions.

I will note that this PR wasn't sufficient to get this all correct. The old disabling of the unused-parameter warning was hiding a bug. Once I turned LTO on and it was able to inline these functions into the calling translation unit, the compiler didn't bother setting up the function arguments. The inline asm needs to indicate that all of function parameters are used by the assembly. I fixed that in 3aecb078.

**Pull request merged**
