### PR TITLE
doc: updated arch figure

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request adds a new figure that shows a more complete view into what Tock encompasses.

### Documentation Updated

- [x] Kernel: The relevant files in `/docs` have been updated or no updates are required.

### CODE REVIEW

**Comment by alevy** [comment]
Importantly, this _does not_ get rid of the previous architecture figure, just doesn't link to it. Is that intentional?

**Comment by alevy** [comment]
In general I'm 👍 for this, though

**Comment by bradjc** [comment]
That figure is still used on the design page that goes into grants.

**Comment by ppannuto** [comment]
I find `C app ported to Tock` vs `App written in Rust` to be a slightly odd distinction (a Rust app wouldn't have to be ported to Tock?)

Otherwise big 👍 here

**Comment by bradjc** [comment]
There are rust apps?

**Comment by ppannuto** [comment]
I get what you're going for - I don't love it but I think I'm also just overthinking it

**Pull request merged**
