### PR TITLE
ADC: Starting on TRD updates

### PR DESCRIPTION
**Pull request by brghena**
Updates to TRD documentation for the ADC.

Pulling this apart from the main ADC PR so that we can have back and forth on it, but still get the ADC stuff merged into Tock to start using it.

### CODE REVIEW

**Comment by brghena** [comment]
These are obviously still a work in progress, but I wanted a PR in to track it and enforce that it can't be forgotten about.

**Comment by brghena** [comment]
This should be ready to go

**Comment by phil-levis** [comment]
A few comments on the ADC interface:

1) A query interface (is_running, is_busy) would be good. This is state that the driver should already have, so providing an accessor to it doesn’t require extra RAM. Doing this would allow a client to potentially be stateless on the underlying driver. I.e., it doesn’t need to keep track of whether there are outstanding calls.

2) Clearly stating the behavior when the driver runs out of buffers is critical. I.e., does it pause, or does it stop? E.g., can you implicitly stop sampling by failing to providing additional buffers, or simply pause sampling? 

3) Changing the return values to (ReturnCode, Options<&mut [u16]>, Option<&mut [u16]>) seems like the best approach to for sample_highspeed. But I’m tempted to think there should be a stop_highspeed as well, to keep the interface unified. It makes using the interface a little harder, but less likely to be used in a buggy fashion (leaking buffers). Can you walk me through the reasoning for the callback/retrieve approach?

I’ll do a detailed editing pass soon.

Phil

**Comment by brghena** [comment]
Thanks for the comments Phil.

1) I generally agree with you. That could be made part of the HIL Adc interface and would be pretty simple.

2) Good point. I didn't really think that through before. The current SAM4L implementation calls `.take().map(...` on the next buffer, so if there isn't one available, it silently stops collecting samples via DMA. However, since there are no more DMA callbacks, even calling `provide_buffer` won't start the ADC again and the only option is to call `stop_sampling`. I propose that if the ADC ever finds itself to be out of buffers that it internally calls `stop_sampling` and returns to an inactive state.

3) The argument for the callback/retrieve approach was simply that I didn't want a duplicate stop function. I think it would be a valid approach to create a `stop_highspeed -> (buffers)`, remove `retrieve_buffers`, and make `stop_sampling` invalid for high speed operations. In my opinion, this would make a lot more sense if we also go the path that you had previously suggested of a main Adc trait and two subtraits AdcSimple and AdcHighSpeed that branch off of it, with `stop_sampling` going in AdcSimple and `stop_highspeed` going in AdcHighSpeed.

I'll be happy to make more detailed changes when you've got more comments.

**Pull request merged**
