### PR TITLE
Cleanup libtock directory structure

### PR DESCRIPTION
**Pull request by alevy**
This just separates `libtock` source files in `src` and `include` subdirectories. No other changes to apps are needed since this follows the pattern for libraries anyway.

### CODE REVIEW

**Comment by bradjc** [comment]
Is this better than the simple mode we have now or heading towards a larger cleanup of libtock? I find when I encounter unfamiliar projects that are structured like this it just feels like adding needless confusion as the .h and .c files can drifter farther and farther apart. It also makes it difficult to tell if there is a corresponding .h or .c file.

**Comment by alevy** [comment]
That's fair. Three points:

1. It's how all of our other libraries are structured, so you gotta learn this structure anyway, and doing it for libtock means it'll seem less magical.

2. If you're building an app out-of-tree (eventually with a pre-compiled version of libtock.a, rather than subrepo'ing the whole tock repo), you'll have to copy the include files. This makes it really obvious that you can just copy the whole `include` directory.

3. It's how C projects are normally structured.

**Comment by alevy** [comment]
@bradjc are you still against this? If so, anyone else wanna come to my aid? If not, should we just close this?

**Comment by brghena** [comment]
With regards to point `1`, I find having all the rust files inside a `src/` directory to be one of the more annoying aspects of Rust and I would do away with it if I knew how. I think having the `c` and `h` files in the same directory feels a lot easier to use than separating them.

I don't hate point `2`, but isn't it already obvious that you have to copy the `.h` files? Or are there `.h` files that wouldn't go in the `include` directory?

For point `3`, do you have evidence for it? Contiki (which I'll admit may not be a good example of an intuitively structured project) does not do so. RiotOs makes an `include` directory, but not a `src` directory, which is the more common usage, in my opinion.

**Comment by alevy** [comment]
> do you have evidence for it?

Not really :/

We can close this

**Comment by ppannuto** [comment]
I spent a little while googling around trying to find any insight into the "right" way to structure a C project and any argument for the `include` folder, I couldn't find anything. I'm not a big fan of the separate folder either personally, so I think closing this makes sense.

**Pull request closed without merging**
