### PR TITLE
Support for STM32F1

### PR DESCRIPTION
**Pull request by george-hopkins**
### Pull Request Overview

This pull request attempts to bring Tock OS to the STM32F1 series. At the moment, the patch still needs some work. As it's my first time working with Tock OS, I'm sure there is a lot of space for improvement. Due to the wide range of processors under the STM32 umbrella, preparing for all variants probably needs some architectural decisions. I'm happy to hand over the patch or to just serve as guideline for a second iteration of the patch.

To avoid one big chunk of new code, this patch attempts to bring STM32F1 to [tier III](https://groups.google.com/forum/#!topic/tock-dev/4qu7P4MX82w). The following features have been implemented so far:
* GPIO (except interrupts)
* USART (transmit only)
* Alarm
* Systick (same as Cortex-M4)
* Clock management

With these features, the example application `blink` runs successfully.

### Testing Strategy

The pull request was tested on a custom board based on a STM32F103ZE. The board runs at 72 MHz with an external oscillator.

### TODO or Help Wanted

- [ ] plan on how to separate the processor families (to ease adding support of new chips and avoid code duplication)
- [ ] testing on popular boards (e.g. STM Discovery or Nucleo)
- [ ] usage of bit handling library¹

¹ Porting to new platforms usually requires digging through lots of registers. Introducing a separate library to manipulate registers would increase the readability and help to avoid bugs (e.g. as used by [tock-teensy](https://github.com/shaneleonard/tock-teensy/tree/master/common/src/regs))

### Documentation Updated

- [x] Kernel: The relevant files in `/docs` have been updated or no updates are required.
- [x] Userland: The application README has been added, updated, or no updates are required.

### Formatting

- [x] `make formatall` has been run.

### CODE REVIEW

**Comment by niklasad1** [comment]
wow, amazing 🙌

**Comment by alevy** [comment]
Wow, @george-hopkins this is great! The STM32 is a super important family to start supporting! Also having cortex-m3 in our `arch`s is important. So really overall this is awesome!

I'll start looking through this to see if I have detailed comments, but a few high level thoughts:

- I think it might be problematic to merge upstream until there is some common hardware we can test on (e.g. so we can test future changes). A nucleo or discovery board is probably ideal since that should be easy for everyone to get. We can wait on that, or potentially we could put this in a separate repo for now. I don't have a strong feeling either way, especially since I, personally, really want STM32 support as a main target eventually.

- This particular chip doesn't have an MPU, which is a bummer. Other STM32s do, so to the extent that this helps port to those chips as well (which I think it does a lot), that's probably ok. The NRF51 doesn't have a standard one either (though there technically is a nordic-specific one we still might try using at some point) but we're kind of moving away from that chip towards the NRF52, which does. It basically means we have no way to isolate processes for now.

- RE:  plan on how to separate the processor families, @niklasad1 did a nice job, I think, with the nrf5x crate. I'm not sure if the STM32 family has as much in common as the NRF5x's do, but if they are similar enough, following that model make sense. Either way though, the trajectory @niklasad1 followed was to just write the port in place until he found himself copying code over between the NRF51 and NRF52 and the figure out how to factor common parts out. I think that worked pretty well.

**Comment by alevy** [comment]
This part of RIOT (which you seem to have contributed to!) seems to imply that the peripherals are pretty similar!

https://github.com/RIOT-OS/RIOT/tree/master/cpu/stm32_common

**Comment by alevy** [comment]
I have a [NUCLEOL152RE](http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-nucleo/nucleo-l152re.html), which has a similar MCU on it, hanging around. I'll try to get this running on that.

**Comment by george-hopkins** [comment]
Thank you for your feedback!

* The missing MPU definitely limits the features Tock tries to provide. Nonetheless, I think the good design of Tock and the safety of Rust itself still makes these processors a good target.

* To further improve the port, I added support for the [Nucleo-F103RB](http://www.st.com/en/evaluation-tools/nucleo-f103rb.html) development board. It is based on a STM32F103RB which is basically the same as the STM32F103ZE. There are just less peripherals and pins available. All registers and mappings are identical (verified by comparing the official SDK). This in turn allowed me to test it on real hardware. Due to the small Flash and RAM, the support for multiple applications is kind of limited.

* To make Travis happy, I added precompiled libraries for Cortex-M3. These were [built on Circle CI](https://circleci.com/gh/george-hopkins/tock/28#artifacts/containers/0).

**Comment by bradjc** [comment]
This one is tricky for me! On one hand we definitely want to support more boards and the STM32 family. On the other, I'm wary of making a non-MPU board a core platform in Tock.

**Comment by Goyapa** [comment]
@george-hopkins 
I'm interested in the STM32 chipset too and would like to contribute.
I bought the STM32F3DISCOVERY board an I will follow japarics book¹ and hope to get a deeper understanding of ARM Cortex-M4 and STM32 in general.

STM32F3
* STM32 Chipset
* Cortex-M4
*  with MPU
What I found so far is "Migrating from STM32F1 Series to STM32F3 Series
microcontrollers"²

¹https://github.com/japaric/discovery
²http://www.st.com/content/ccc/resource/technical/document/application_note/8e/c8/8d/e3/ee/ff/44/e6/DM00073522.pdf/files/DM00073522.pdf/jcr:content/translations/en.DM00073522.pdf

**Comment by alevy** [comment]
> So what I see what stands out is to migrate STM32 crates and map with Cortex-M4 crates.

In fact, the tricky part will really be the peripherals (e.g. GPIO), which are different. M0 vs. M4 difference is _mostly_ handled by the `arch` crates.

**Comment by alevy** [comment]
Two other notes:

1. YMMV using Jorge's tutorial as a good intro for building a port for Tock. The tutorial is very good, but from memory it operates at a high enough level of abstraction that it may not translate very well to Tock (and vice versa). Still might be a good way to get your hands dirty.

2. There was some chatter on IRC about using the STM32F4 (rather than 3) discovery board. I believe the chips are fairly similar, but the the F4 board is a bit more featureful (has a microphone and accelerometer at least). It would be good to join these efforts together? Unfortunately I don't know that person's GitHub handle, but they are OmniMancer on IRC (the mailing list would also be a good place to coordinate).

**Comment by george-hopkins** [comment]
I can understand the issues related to integrating a non-MPU architecture. I'm happy to move my work out-of-tree (there might be even an [official guide](https://github.com/helena-project/tock/issues/699) to do so which is great!) and work from there. That would allow us to clearly draw a line between those architectures which implement all the features/guarantees Tock provides and those which lack in some areas (e.g. MPU).

@Goyapa Support for more STM32 boards would be awesome! Feel free to take a look or base your work on what's already there. I think it would be a good candidate for a core architecture as the board is widely available and the CPU seems to have all the features run a fully-equipped Tock OS.

**Comment by alevy** [comment]
OK, let's make an executive decision here.

Option one is to merge this PR more or less as is. Maybe I or someone else will take a quick pass on the code again and we can also test with Nucleo. But generally I think the quality is good.

Option two is to do this work in a separate repo (@george-hopkins can manage the repo, or we can make one in the @tock organization). One particular benefit of this might be that it could make sense to experiment with various ways to separate process families for STM, and that probably shouldn't block on our PR queue while it's iterating.

@bradjc? @brghena? @ppannuto? @niklasad1? @george-hopkins?

I'm ambivalent.

**Comment by alevy** [comment]
(Ambivalent, but leaning towards merging)

**Comment by bradjc** [comment]
I vote we move the `board/nucleo` folder to a separate repo, add a README to `chips/stmf1` explaining the current state, and merge.

**Comment by phil-levis** [comment]
I'd suggest merging. The main repository is where people will start, and it lends a certain degree of faith in the code. It might be useful to lay down some guidelines on what it takes to merge new code into the repo, e.g., an informal commitment to support the code for at least a year. If the developer wants to move on after a year and no-one is willing to take the torch, then moving it out would be safe.

**Comment by niklasad1** [comment]
I agree with @phil-levis and vote for merging also STM is commonly used chip and may increase possibility for people to play around with Tock!

Also I think the discussion about supporting non-MPU platform is interesting because currently we support nRF51 which is non-MPU and the MPU is not enabled for nRF52 yet.
No MPU, harms dependability in my opinion so it's a trade-off between increasing the reach of Tock v.s. dependability.

Additionally, in the future if only userland Rust is supported I'll be much more open to support non-MPU platforms (but yes memory allocation, syscalls etc might need memory protection)

**Comment by bradjc** [comment]
We have the nRF51 as a board, but mostly for legacy reasons and it seems all active development is for the nRF52. I don't see that as a precedent we want to lean on.

My main concern is that having mainline support for a specific platform would encourage people to use that particular board, when a roughly equivalent one would be a better choice and make the text in the first paragraph of the readme accurate.

**Comment by alevy** [comment]
Just to clarify, I don't think anyone is suggesting there _shouldn't_ be ports of Tock to non-MPU chips, or even that we wouldn't point people to them, but just that the main repository wouldn't include.

A separate note is that there _are_ plenty of MCUs in this family that _do_ have an MPU (just not the one currently used in this PR).

**Comment by niklasad1** [comment]
Right right, but I want consistency i.e., if we decide to move this PR to a separate repo then IMO at least nRF51 should be moved to separate repo as well. Then clearly state that `only` platforms that have mainline support/MPU are in the main repo and other ports can be found `somewhere`

Then, the issue is to maintain these repos and keep it up to-date with the `main Tock repo`

**Comment by Malex92** [comment]
Nice Work!

I work on the same topic for the EK-TM4C1294XL Board. Did you use any debugger for error searching?

**Comment by george-hopkins** [comment]
@Malex92 Fortunately, almost everything worked out of the box. One time I accidentally copied a register value instead of taking a reference (thus all writes were optimized away). After hooking up OpenOCD and gdb over JTAG the issue could be resolved quite fast. I have not yet looked into loading symbol files to simplify debugging, the others can probably tell you more about that approach.

**Comment by alevy** [comment]
I've created a new (empty) repo in the tock organization: https://github.com/tock/tock-stm32

Let's put all of this code there for now. There is at least one more person working on an STM32F4 port that has working code, which can go there as well. We can merge upstream at any point in the future too, but I'm very uneasy with this all staying in PRs for now. We need at least a central place to point contributers with STM32 in mind for now.

I'll help bootstrap the repo administration (e.g. setting up dependencies and the structure etc), but would be happy with someone working on STM32 actively taking over stewardship of the repo at some point.

**Comment by Grawp** [comment]
What is the advantage of creating a new repo instead of a new branch(es) in the current repo? As far as I can tell there are no necessary changes to the existing crates or build infrastructure needed by STM32Fx.

**Comment by ppannuto** [comment]
I think the discoverability of a repo is much greater than a branch. Plus it's a pathway to give the STM folks a little more autonomy instead of being blocked on mainline Tock developers to approve/merge chip-specific changes.

**Comment by alevy** [comment]
Closing this on account now that these changes have been moved to tock/tock-stm32

**Pull request closed without merging**
