### PR TITLE
nRF52-DK 

### PR DESCRIPTION
**Pull request by niklasad1**
Hi,
This is a PR to support nRF52-DK in Tock.
There alot of files added but I will try to summarize the important parts:
* I use the same build system as for nrf51 thus `make TOCK_BOARD=nrf52dk flash` builds and flashes the board.
* Currently UART(TX only), Timers and LEDs are supported. Most of it is copy-paste but the UART code is "new" and uses the DMA instead of send byte-by-byte. Additionally I explicitly turn off interrupts in the interrupt_handler which the nRF51 does not. I don't understand why 😃 
* Important directories: 
..*[boards](https://github.com/niklasad1/tock/tree/nRF52832/boards/nrf52dk) 
..*[chips](https://github.com/niklasad1/tock/tree/nRF52832/chips/nrf52)
* I have tested the implementation successfully with:
..*[blink](https://github.com/helena-project/tock/tree/master/userland/examples/blink)
..*[printf_long](https://github.com/helena-project/tock/tree/master/userland/examples/tests/printf_long)
..*panic!()
..*debug!()

### CODE REVIEW

**Comment by jkingyens** [comment]
I'd love to try this out. Is this PR compatible with nRF52840 preview DK? or the kit for nRF52810 and nRF52832 chips?

**Comment by alevy** [comment]
@jkingyens It's meant for the kit, but it ought to work with minimal changes (if at all) for the nrf52840 preview dk as well. Note that, of course, it doesn't have any 802.15.4 support (which is new on the nrf52840 chip). I _think_ the only different _might_ be the pin configurations.

**Comment by niklasad1** [comment]
yee, that's a good point I haven't checked the pin configurations for nRF52840 and nRF52810 yet.

**Comment by alevy** [comment]
@niklasad1 Just tested and it works as advertised. Let's merge and kind of assume for now it's _probably_ not perfect, but probably just as good as the nrf51dk and good to merge since it's a new board. Nice work!

@jkingyens I tested it on the NRF52840 preview DK just now. The UART and core work fine, but the LEDs are annoyingly on different pins, so those don't work out of the box (in @niklasad1's defense, the name `nrf52dk` is _still_ correct since this is just a _preview_ dk, but we'll probably have to do some better naming when the official one comes out).

In any case, good enough to start playing with, and the changes to adjust the pins should are super minimal (lines 15-18 in `boards/nrf52dk/src/main.rs` and it works perfectly)

**Comment by alevy** [comment]
Also, I just got an NRF52 Thingy in the mail, which should serve as a really good platform once we implement I2C for the NRF52. Pretty easy for people to get their hands on and pretty fully featured. We should be able to build a good sensor network app with BLE advertising (at least) pretty simply, and go from there!

**Comment by niklasad1** [comment]
Update: I have checked the pin configuration for NRF52840 preview DK and it is not compliant with nRF52-DK as @alevy stated. 

nRF52840 uses port 0 (32 pins) and port 1 (16 pins) and has 48 pins
nRF52832 uses only port 0 and has 32 pins.

I will add some notes about this in the [/boards/nrf52dk/src/main.rs](https://github.com/helena-project/tock/blob/master/boards/nrf52dk/src/main.rs)

@alevy perhaps we should add another board crate for NRF52840 preview DK and NRF52 Thingy and use the same underlying chips crate? Or what do you think?

But for now I will focus to port new stuff to nRF52-DK.

**Comment by alevy** [comment]
@niklasad1 Absolutely those should be in different boards. I certainly didn't mean to imply that the new board you made should somehow fit _any_ board.

When the final development kit (not the preview) comes out for the nRF52840 we'll see if the pins still don't match and the might just have to rename the nrf52dk board to something more specific if it's ambiguous. It'll probably make sense to make a new board for the 52840, ideally with the same chip (just different features enabled or something).

As for the Thingy, yeah, we should probably make a new board sometime soon, though it might be fine to start by developing it out of tree too.

In both cases, we should just do this lazily, though. No point in prematurely optimizing :)

**Pull request merged**
