### PR TITLE
Add capsule for si7021 temp + pressure sensor

### PR DESCRIPTION
**Pull request by alevy**
Taken from the signpost repo. I set @bradjc as the author of the commit since I really just downloaded the file from his signpost commits.

### CODE REVIEW

**Comment by alevy** [comment]
I'm getting poor measurements atm: over 100&#8451; and 100% humidity after dividing the results by 100. @bradjc any ideas?

**Comment by bradjc** [comment]
Nothing is coming to mind off the top of my head. I'll try this when I get back and have access to that sensor again.

**Comment by alevy** [comment]
OK, I can't really find where the initial measurement command is actually being sent (`time::Client#fired` just issues a `read`), so that might be it.

@moshih is going to be taking over drivers for the sensors on the Imix, so maybe he can get to the bottom of this.

**Comment by alevy** [comment]
According to @shaneleonard, the issue may very well be a hardware issue on the Imix. @bradjc do you have any way to confirm that the driver, in general, works? Since I just copied it from the signpost repo, if it works there it should work here...

**Comment by bradjc** [comment]
Ok I finally got things to load on the board that I have that has the SI7021, and I get correct temperature and humidity readings.

My two questions:

1. Why does it reuse syscall number 5 (which storm uses for nRF)?
2. Why are the si7021.c/h files buried in the imix apps folder?

**Comment by bradjc** [comment]
I made some changes that I think are useful:
- Make the driver number 10
- Put a test app in the main examples folder
- Put the helper .c files in libtock
- Rebased on master

The last two commits should really be squashed if you want to keep my changes.

**Pull request merged**
