### PR TITLE
RFC: errata / "micro boards" ?

### PR DESCRIPTION
**Pull request by ppannuto**
This includes #649 - only the second commit is relevant here.

Errata no. 32 for the nrf52832 rev A makes it such that LEDS 2 and 4 don't work correctly. Unfortunately, the fix basically shuts off debugging:
http://infocenter.nordicsemi.com/pdf/nRF52832_Engineering_A_Errata_v1.2.pdf (p20)
Subsequent silicon revisions fix this bug:
http://infocenter.nordicsemi.com/pdf/nRF52832_Engineering_B_Errata_v1.3.pdf (p24)

More generally, how should we handle things like this in Tock?

One solution is cfg-gating fixes like is done here, then having the build system build all board revisions, and use an attribute to decide which hardware rev. I _think_ you could automate all of this by listing cfg features in the chip's Cargo.toml and pulling them out during build.

While this is maybe a bit heavy-handed for some LEDs, there's more drastic chip errata that I imagine will come up in the future and we'll want some mechanism for handling this. At the same time, I'm very wary of effectively re-introducing `#define` hell via `cfg` :/

### CODE REVIEW

**Comment by bradjc** [comment]
My two cents: we should just use stable hardware, and not complicate Tock to support this case.

**Comment by brghena** [comment]
I know this is just kicking the can down the road, but following up on Brad's comment, is any selection actually necessary in this case?
 * Does any platform use either of the engineering models of the nRF52832?
 * If so, is it fine to just "shut off debugging" on all nRF52832s?

I could see this being an option that would have to be selected at init time in platform `board.rs` files. Seeing as they are the location where pins are selected, it feels that they are most capable of making this decision.

In general, when we hit configuration differences, we've so far expected the platform files to handle that in one way or another. Having used C pretty considerably, it feels like including `cfg` boundaries everywhere is not the option we want in Tock.

**Comment by bradjc** [comment]
@ppannuto ?

**Comment by ppannuto** [comment]
Okay, so went down a bit of rabbit hole around this today. Inspired by https://devzone.nordicsemi.com/question/99037/is-there-a-possibility-to-read-out-the-hwid-and-map-it-to-ic-revision-and-build-code-nrf52/, I looked into detecting what core we're on and automatically doing the right thing. Unfortunately, the `INFO.VARIANT` field is "Unspecified" for Preview hardware it seems, so there's no way to detect it and automatically do the right thing.

In the more optimistic times, I implemented access to the FICR registers, which is still useful. Opened that separately as #696.

**Pull request closed without merging**
