### PR TITLE
container: stop using Owned with enter, each

### LINKED ISSUE #538: Owned<T> should either free on drop (for Allocator) or not (for Container)
`Owned<T>` is produced by operations like `enter` on a `Container`. I notice that it has a `Drop` impl, which (for app containers) winds up calling `app.free(...)` [here](https://github.com/helena-project/tock/blob/master/kernel/src/container.rs#L69).

It so happens that `free` on a `Process` is [currently a no-op](https://github.com/helena-project/tock/blob/master/kernel/src/process.rs#L1127) without documentation, but I assume based on the name that it's intended to free the associated buffer.

But a new `Owned<T>` is created and dropped for each container access. For example, during `enter`, it gets dropped [here](https://github.com/helena-project/tock/blob/master/kernel/src/container.rs#L190). This means you'll call `free` on every container access.

Is this intentional?

### PR DESCRIPTION
**Pull request by cbiffle**
This introduces another smart-pointer type, Borrowed, for the case where the
memory is not actually owned but borrowed. I would have preferred to just use
`&mut T`, but capsules are relying on the value including an `app_id`, so this
seemed like the smallest delta.

Fixes #538.

### CODE REVIEW

**Comment by alevy** [comment]
(there was a `rustfmt` error in travis, so I just fixed it, it was tiny)

**Comment by cbiffle** [comment]
In practice, capsules getting `app_id` from the pointer is kind of weird -- they typically are already manipulating an `AppliedContainer`, which also contains the `app_id`. Lots of unnecessary copies. But you can't generally get to the `AppliedContainer` `app_id` at the point where you need it because all of the `AppliedContainer` is borrowed by `enter`.

The larger-delta fix I considered: change the `Iterator` impl for `Container` to yield `(app_id, &mut T, allocator)` triples. Since everyone iterating over a `Container` seems to immediately `enter` the `AppliedContainer` they receive, this would remove a step.

**Comment by alevy** [comment]
Interesting. That's @ppannuto's domain, but we have a commend `make format` which makes things at least consistent.

**Comment by ppannuto** [comment]
> Few of the files seem to conform to the rustfmt.toml in the project root.

Hmm.. this could be a delta in behavior between modern rustfmt and v0.7.1; we pinned a version a long time ago since there was too much upstream churn. At the time, I believe the behavior was to use all of the rustfmt's default except those overridden by the config, which is why it may not look like the config is doing much.

In practice, deleting the root config only seems to affect the panic string in `chips/sam4l/src/lib.rs` (likely the `format_strings = false` choice -- I'm not surprised to see no change from disabling `reorder_imports = true` as the default behavior is to ignore iirc)

Don't want to derail the discussion here for formatting stuff, feel free to jump on IRC ([#tock on freenode](https://kiwiirc.com/client/irc.freenode.net/tock)) or open a new issue if you think there's something wrong here.

**Pull request merged**
