### PR TITLE
N rf51822/working blinky

### PR DESCRIPTION
**Pull request by utkarshapets**
Added:
uart.rs for the nrf, basic TX and RX functions
platform/lib.rs includes initialisation of UART

### CODE REVIEW

**Comment by alevy** [comment]
Please update the title and description of the pull request to reflect what's being merged.

**Comment by alevy** [comment]
Please remove all unrelated files (random_number app, timer, uart_old, etc) and all the temporary files (there are a bunch of tmp files ending in `~`)

**Comment by alevy** [comment]
The pull request should be against the `master` in the this repo (the helena-project repo) and I expect them to only include changes to:

  * `src/platform/nrf_pca10001/lib.rs`
  * `src/chips/nrf51822/uart.rs`

I could be off by a file or two, but basically a handful of files as opposed to 32.

**Comment by utkarshapets** [comment]
There are differences in the Makefile in the master and working-blinky branch. I can simply commit these two new files, but they wont work if merged with master.

**Comment by alevy** [comment]
Are those differences important for your UART changes to work?

**Comment by utkarshapets** [comment]
Yes, with the Makefile in master, there is no rule to make a bin file, and I guess the elf file too.
The new branch was created specifically so I could make apps. There were many issues, I do not recall all of them, I can try to figure out what they are, but in the meanwhile maybe I should merge with working-blinky?

**Comment by alevy** [comment]
No you should not merge with working-blinky

**Comment by utkarshapets** [comment]
Alright, I will see the differences in the files and try to create a version that will work

**Pull request closed without merging**
