### PR TITLE
Fill in ADC trait for SAM4l. Use ResultCode. AdcContinuous unimplemented. 

### PR DESCRIPTION
**Pull request by phil-levis**

### CODE REVIEW

**Comment by alevy** [comment]
@phil-levis is this WIP?

**Comment by phil-levis** [comment]
Ooops, forgot to format the code.

It's work in progress (continuous needs to be implemented), but also in a stable state. I thought, following your suggestion, I would focus on the RF233 for now, rather than doing AdcContinuous. But I think it's important to have the actual trait in hil/ (not commented out) and have at least a skeleton in the implementation (so people can see what it's like).

**Comment by bradjc** [comment]
I rebased and added ADC Continuous to the Wiki.

**Comment by phil-levis** [comment]
Can someone merge this? I'd like to start using ResultCode for the RF233. Or am I supposed to merge it?

**Pull request merged**
