### PR TITLE
Rename built output folder to "build"

### PR DESCRIPTION
**Pull request by bradjc**
1. It is pretty straightforward to see how built output ends up in a
folder called "build".
2. "target" is overloaded in embedded systems; I would expect that
folder to contain information about how to load an app onto a specific
target.
3. It's truly awful that cargo only reads config information from hidden
files. I'm not sure I've run across a more user un-friendly thing than
putting key information in a file and then intentionally hiding it.

### CODE REVIEW

**Comment by ppannuto** [comment]
Ohhhh.... Ugh... Oy... it's a dangerous step towards TinyOS's single most evil, confusing, awful, cruel, I spent literally a week and couldn't figure it how the magic happened, design decision ever: the `.platform` file.

1. Built output is going to show up somewhere, `build` is fine, so are most other nouns IMHO.
2. That's one thing that could be 
3. It is truly truly is evil.

More than anything, I'm not convinced that doing something different than what Rust does out of the box is worth fixing Brad's confusion here, especially if it confuses people who know Rust [admittedly a smaller user base than those with embedded background], feels like then you're losing one way or another. I don't find the use of target at all confusing. If we never ever put anything else in the world's single most evil configuration file, maybe I'd be okay with this, but I have some scars and am pretty adverse to opening that Pandora's box.

[For context, this is a debate recently held in person in lab, summarized-ish in github form]

**Comment by ppannuto** [comment]
nit: if you do move forward, you should pull `target` out of the `.gitignore`

**Comment by bradjc** [comment]
`_target` would also be fine.

**Comment by alevy** [comment]
`target` is so named because it's target specific and we only end up with a `target/target` folder because our target specifications are currently just named `target.json` (target target target target...) 

Would it make a difference to you, if instead it built into `target/sam4l` or `target/arm-thumbv7em` or something?

If not, I'd prefer for this to be a board specific choice (it can just as soon go in the board's directory, so, e.g. `boards/sam4l/.cargo/config`)

**Comment by brghena** [comment]
It's the first target that's the problem. If you're just exploring the Tock directory, it's not obvious that it's a build output folder rather than a folder with source or libraries or something important. Could it be renamed to `_target`?

As for the inner folders, I think it would be great to rename the `target.json` files to `sam4l.json` and `nRF51.json` or something like that. The target/target thing is strange.

**Comment by brghena** [comment]
Pulled up to master. Also updated Makefiles and `target.json` files.

@alevy What are your thoughts?

**Comment by alevy** [comment]
OK, this is fine. But I think we need to just move the target specification (formerly `target.json`) and the linker scripts to the board directories rather than using this "cute" hack in `build.rs`. Of course we can have example ones in the chip crate's source code (conveniently symlinked from the board directories in our repo).

The problem is that if another board developer comes along and tries to use the `sam4l` crate, they had better make sure that they also change their built output folder to `build`, or else cargo won't find the linker script.

Moving both puts a bit more burden on the board developer to copy those files into their crate, but it avoids an annoying hack anyway, plus it provides some flexiblity if the board developer wants to make different decisions about how to layout memory (e.g. if they aren't using the storm bootloader, they'll need to put the vector table @ 0x0 instead of 0x1000).

**Comment by alevy** [comment]
On the call today, we decided not to do this and instead to stick with the Rust defaults. However, #119 makes it so that a particular board (e.g. Signpost) can choose to do whatever it wants, including this.

**Pull request closed without merging**
