### PR TITLE
Add MAX17205 Driver

### PR DESCRIPTION
**Pull request by bradjc**
Also used on Signpost.

### CODE REVIEW

**Comment by alevy** [comment]
Is this basically just copy-pasted from Signpost? If so, do we want to just merge as is an iterate as we feel useful? Or do we want to iterate within the pull request?

I'm asking because I have stylistic comments (mostly requesting more descriptive comments, etc) as well as some questions about the organization (e.g. whether this would be better split up into a peripheral driver and system call driver given our experience with the accelerometer).

However, I also don't really mind merging first and iterating later as this clearly works reasonably well enough for signpost.

**Comment by alevy** [comment]
BTW this question kind of also goes for the other outstanding driver pull requests from @bradjc

**Comment by brghena** [comment]
It seems to me that if there are changes we want to make these better technically or aesthetically, we might as well handle them now. It's not like we're going to have more time in the future.

**Comment by ppannuto** [comment]
Agree with @brghena. This is code that we know works, but would like to upstream. It's kinda the definition of the upstreaming process to massage code into something that's compatible with the upstream code base / ideals. _Especially_ the stylistic stuff, as we'd like code in Tock master to be representative of best practices as much as possible IMO.

**Comment by alevy** [comment]
OK, will do a proper review of these and the other drivers then

**Comment by alevy** [comment]
Ditto here as with #359 (+ fix conflicts)

**Comment by bradjc** [comment]
> Ditto here as with #359 (+ fix conflicts)

@nealjack Can you help with this?

**Comment by bradjc** [comment]
Updated.

**Pull request merged**
