### PR TITLE
SAM4L Low Power: Manage TWIM/S clocks

### PR DESCRIPTION
**Pull request by alevy**
Ref: #470 

This change only leaves the TWIM/S clocks enabled when currently operating (i.e. a transaction is happening or we are listening for a transaction from an I2C master).

This does not yet implement low-power operation when the I2C device is just listening. That will be for another PR (it's a bit more involved).

It is possible, with these changes to, e.g. run the `sensors` app successfully with the SAM4L dropping into deep sleep between sensing events (which occur every second on that app).

### CODE REVIEW

**Comment by alevy** [comment]
@adkinsjd it would be great if you could test that I haven't broken I2C device and, specifically, the switching between master and slave functionality on Signpost (or help me figure out which workload to run to make sure I've covered the important cases).

**Comment by alevy** [comment]
Pinging @adkinsjd @brghena @ppannuto @nealjack

**Comment by ppannuto** [comment]
@brghena could you toss some text here describing the state of the world from your I2C testing a little while ago?

I think we should try to get https://github.com/lab11/signpost-software/pull/38 merged to catch up signpost before we start digging into this -- @adkinsjd you said two PRs, #652 obviously, but which was the other that this is blocking on?

**Comment by adkinsjd** [comment]
I didn't submit the other PR, but I was referencing https://github.com/helena-project/tock/tree/add-drivernum, which Signpost now depends on. I didn't submit the PR because it didn't seem like it was needed/things were still changing, but I can if you'd like.

**Comment by adkinsjd** [comment]
Nearly all of the work for merging is testing, which needs to be done fairly extensively, especially on things like the ambient board which is using new interfaces.

**Comment by adkinsjd** [comment]
I think that power should be tested on both TWIM and TWIS before this is
merged. I don't think low power operation was ever confirmed (specifically
for TWIS), and it seems reasonable to ensure functionality and low power
operation given the staleness of the PR.

**Comment by alevy** [comment]
@adkinsjd do you have any ideas for ways to test TWIS? We don't have anything that's TWIS on Hail or imix, and I can use Signpost but I've not had good luck testing low-power on Signpost.

**Comment by adkinsjd** [comment]
It's a bit difficult to get "good" power numbers on Signpost due to all of the other ICs that are also powered, but I think a possible strategy is measuring power on a signpost board (probably ambient or audio) in a state we know is low power, like a loop with serial, then add TWIM, then TWIS and look at the power difference. I have started doing that now, but if I run into problems I don't have cycles to devote to debugging.

**Comment by adkinsjd** [comment]
The below application draws 180uA on ambient until the i2c_master_slave_write call, where it starts drawing ~11ma. Ambient board was built with the kernel on this branch.

```
 16   printf("\n[Ambient Module] Sample and Post\n");                               
 17                                                                                 
 18                                                                                 
 19   // perform main application                                                   
 20   uint8_t data[20];                                                             
 21   i2c_master_slave_set_master_write_buffer(data, 20);                           
 22                                                                                 
 23   while (true) {                                                                
 24     printf(" * Initialization complete\n\n");                                   
 25     delay_ms(10000);                                                            
 26     i2c_master_slave_write(0x20, 20);                                           
 27     delay_ms(10000);                                                            
 28   } ```

**Comment by bradjc** [comment]
This PR shouldn't make the I2C receive low power (description says that's forth-coming). I think the question is what is the power after an I2C transmission, and does I2C receive still work.

**Comment by adkinsjd** [comment]
Correct me if I'm wrong, but I believe that's exactly what the code above and my power results show is not working.

**Comment by bradjc** [comment]
Well it draws more current, but does it receive packets? The current wasn't expected to go down.

**Comment by bradjc** [comment]
Ohh I'm dumb it's a write call.

**Comment by adkinsjd** [comment]
I'm not trying to receive packets at all. I am just transmitting. If this PR was working the power would go down after transmission, and that is not happening.

**Comment by alevy** [comment]
@adkinsjd it's important to setup the board properly, since _most_ other controllers don't implement low-power support yet, and if any of them are on, it won't work.

I can (and will) test power draw for I2C master. The important bit to test is I2C slave _functionality_, which is harder for me since... i don't have an I2C slave application for Hail or imix

**Comment by adkinsjd** [comment]
I suppose I don't understand what I could change in the board file. It is
successfully going into low power mode pre-I2C call, then not re-entering
low power mode after the I2C call. Doesn't that show that the board is
capable of doing low power, or is there a subtle change to the I2C setup
that could make just the I2C fail?

**Comment by alevy** [comment]
@adkinsjd it's been a while, so i don't remember the details exaclty, but I also don't know exactly the board setup you're using. I also haven't followed the i2c_master_slave driver throughout it's path, just the drivers that use I2C master exclusively (and I2C slave is trickier to get to low power for reasons we discussed at the time).

Again, I will test power specifically when I can, and when I do that I'll detail exactly what is required; what works, and what doesn't work. (Or I'll fix it)

On the other hand, I'm unable (well that's strong, but I'm not set up for it) to test I2C slave on Hail or imix, and this PR _does_ fiddle with enabling/disabling clocks. In principle, if the clock isn't re-enabled at the right time, it could break functionality (the controller would appear to stop working). I don't _think_ that's the case, but there's no replacement for actually testing ;)

**Comment by alevy** [comment]
OK, thanks @adkinsjd

**Comment by alevy** [comment]
I measured power on imix running this branch's kernel and the `sensors` app, using a 30kOhm resistor (specifically using [CurrentSense](https://github.com/lab11/CurrentSense)).

I had to modify imix significantly to remove drivers that wouldn't let it go into deep sleep since the controllers they rely on don't know how to turn off yet. My version was left with: light, temperature and humidity drivers, console, gpio, alarm and led. I removed all unrelated initialization. I also confirmed the sam4l was periodically going into deep sleep by adding a `debug!` message before the call to `set_deep_sleep` in `chips/sam4l/src/chip.rs#prepare_for_sleep`.

newfile1

The four spikes are measurements for light, temperature and humidity, followed by the `printf` in the sensors app. The baseline is around 1V~=300uA, which is high (should be two orders of magnitude lower), but I believe that's an issue isolating power for the SAM4L from other subsystems on imix.

**Comment by alevy** [comment]
A slightly more reasonable power measurement after hooking up the rest of the board to separate power to try and minimize leakage from the SAM4L. Now the low-points are ~60uA:

newfile1

**Comment by adkinsjd** [comment]
Are you running an app with an I2C master call during this test or just
running the kernel?

**Comment by adkinsjd** [comment]
Oh I see you are running the sensors app. I will attempt to replicate.

It would be nice to creat a test app that just calls
i2c_master_slave_write, and if that doesn't work figure out the mismatch
between that capsule and the sensors app.

**Comment by ppannuto** [comment]
I have that! In the stuff will and I are doing. I’ll pull out those commits
and PR

**Comment by alevy** [comment]
> It would be nice to creat a test app that just calls i2c_master_slave_write

I agree, that would certainly be useful too

But to calrify, the driver that exposes `i2c_master_slave_write` is _not_ the driver used for most I2C calls (as far as I know, it's _only_ used for Signbus). I haven't looked into it, but it's complex enough that I wouldn't be surprised if it did something silly (i.e. reasonable to fix once identified) that makes the kernel unable to go into deep sleep.

_If_ that's the case, I'd suggest fixing that separately (though I think @ppannuto might be taking over this PR, in which case, whatever he wants to do is fine by me).

Though, it may all be hunky dory and just a matter of removing non-deep-sleepable-yet drivers from the board configuration.

**Comment by alevy** [comment]
@ppannuto since you've been working on low power for TWIM _and_ TWIS on separate branch, what should we do with this PR? Should we discard it until your branch is ready? Should we merge it (maybe your branch is based off this one)?

**Comment by ppannuto** [comment]
I think we can close this one out and the other branch will supersede it. The other branch isn't PR-ready yet -- unfortunately I'll be away from equipment to validate power draw until early in the new year, but hopefully I can clean up the implementation so things are ready by then.

**Pull request closed without merging**
