### PR TITLE
Remove need for bootloader to init clocks

### PR DESCRIPTION
**Pull request by bradjc**
So I basically went through what `sysclk_init` in the ASF does and copied it. Code is not pretty right now, but wanted to get this out there because after very first testing it seems to work.

What I can't figure out is why I have to set the multiplier to 1563 instead of 1464 (or 48000000 / 32768).

### CODE REVIEW

**Comment by immesys** [comment]
The bootloader does some other stuff too that is useful, like calibrating
the 32khz RC oscillator. Without this you may have some baudrate problems.

**Comment by alevy** [comment]
@immesys do you remember what the main things the bootloader does? Is the code in https://github.com/helena-project/storm_bootloader_reference up do date?

**Comment by immesys** [comment]
I'll push the latest code to that repo. The only things I think I added after then was configuring brown out reset and calibrating off the radio clock

**Comment by bradjc** [comment]
OK added magic `0x001d0015` calibration constant and panic! printed correctly with 1464 multiply value.

**Comment by brghena** [comment]
I'll move this panic! blink commit to it's own PR

**Comment by shaneleonard** [comment]
@alevy Thanks for the head's up.

**Comment by alevy** [comment]
FWIW, on the Imix I was able to run this version of the kernel without a bootloader + the blink app and it seems to all be working fine.

**Comment by alevy** [comment]
... and the sensors app on the firestorm.

**Comment by bradjc** [comment]
Alright from my end this is ready to go.

**Comment by bradjc** [comment]
Alrighty how does that look.

**Comment by alevy** [comment]
Yeah, looks good. I'm just going to do a rustfmt pass then merge it.

**Comment by alevy** [comment]
There is some issue with travis related to rustup. I'm guessing it's related to the new 1.12 release that somehow mucked with the rustup.sh script we're relying on (other projects have the same issue). It's unrelated to this pull request. I think we're safe merging, and I'll fix this separately.

**Comment by ppannuto** [comment]
@alevy re Travis and rustup, in the background I've been playing with
moving Travis over to their container infrastructure and ran into this as
well. [motivation: builds are much faster] I think it's Travis CI's fault,
when Travis installs rust, it pulls down rustup from
https://static.rust-lang.org/rustup.sh, which seems to be an old version
(the copyright is 2015), as opposed to https://sh.rustup.rs where our
README currently directs people to grab rustup from.

I've briefly worked around this in the `travis-container` branch by
dropping the `language` key so Travis thinks it's a ruby project and
doesn't try to install rust, and then manually calling the right rustup.

I imagine that Travis and/or rust will fix soon-ish though, so the
workaround probably isn't needed.

**Pull request merged**
