### PR TITLE
nRF51822: Auto generate peripheral interrupt vectors and registers

### PR DESCRIPTION
**Pull request by lizardo**
While implementing timer support for nRF51822, I found too boring and error prone to write this code by hand, so I wrote a Python script which used the excellent CMSIS-SVD project to generate this code for me.

In theory, it can be applied to any other platform which has a SVD model (most have, as those CMSIS headers are generated from them). SAM4L specifically does not seem to be supported by CMSIS-SVD at the moment, but if you can find the SVD file for it (usually buried somewhere on the SDK installation path), you can contribute to the project via pull request. Then nRF51_codegen.py can be made more generic.

### CODE REVIEW

**Comment by 0xc0170** [comment]
+1 for the generator. If there are python scripts around, we could add setup script to get required dependencies, or at least for now you could try to import cmsis-svd module and report a descriptive error if it's not in the system..

The entire startup crt1 file can be auto generated. We can consider using python templates, like jinja2 or just as you did write to a file. I find jinja2 as easy to use. There can be a template for ARM architecture, which adds ARMv6/v7 common (like vectors) + platform specific vectors. There might be needed some platform init specific code.

Regarding volatile cell which was added here to the common code, we might consider to distinguish between read-only/write-only/read-write registers?

**Comment by lizardo** [comment]
@0xc0170 

I'll add a try/except to print a descriptive message on ImportError. Thanks for the suggestion! For now, I think setup.py would be too much, maybe if it becomes some sort of "platform port bootstrapping" tool...

Actually, crt1.c can be even rewritten in Rust. I've seen this approach in other "bare metal" Rust projects (where there is only Rust or Rust+assembly code) and the generated assembly is not that bad. I'll create an issue so we do not forget it.

Jinja2 templates are a good way to decouple the model from the "view" (i.e. generated Rust/C code). In fact, that reminded me Yasha (https://github.com/kblomqvist/yasha) already supports SVD models through CMSIS-SVD! There is one example for nRF51 that generates zinc ioreg! macros: https://github.com/kblomqvist/nrf51.rs/blob/master/nrf51.rs.jinja. I will create an issue, but I have no short term plans to look into it (my TODO list growing too big...), so feel free to work on it if you want :)

I remember seeing at least one project with VolatileCell like wrappers with RO/RW/WO variants, but I can't find it now. I believe it is a great addition as it provides more compilation time safety (which is the best we can provide in resource constrained MCUs). Adding an issue for that as well.

**Comment by 0xc0170** [comment]
Here's a startup written in rust, I wrote it for kl25z demo : https://github.com/0xc0170/frdm-kl25z-rust/blob/master/init.rs, that was another thing I wanted to propose , thanks @lizardo for reminding me :)

And that R/W volatile cells, it's also there, however I did not use it much

**Comment by alevy** [comment]
@0xc0170 ported the firestorm's startup script to Rust (now i master). Should be straight forward to do the same thing for the nrf.

**Comment by 0xc0170** [comment]
@alevy +1

**Comment by Malex92** [comment]
Hi lizardo,

I think this approach is very interesting, but when I want to execute the python-script I am always facing following error message: 

C:\Users\Alexander\Downloads\tock-4053390a352c8424250cb8981a0bfff6edcb16d1>python nRF51_codegen.py
Traceback (most recent call last):
  File "nRF51_codegen.py", line 118, in <module>
    main()
  File "nRF51_codegen.py", line 113, in main
    peripherals = get_peripheral_registers(parser, ["GPIO"])
  File "nRF51_codegen.py", line 72, in get_peripheral_registers
    if register.dim:
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python36\lib\site-packages\cmsis_svd\model.py", line 266, in __getattr__
    return self._lookup_possibly_derived_attribute(attr)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python36\lib\site-packages\cmsis_svd\model.py", line 85, in _lookup_possibly_derived_attribute
    raise AttributeError("Requested missing key")
AttributeError: Requested missing key

I use the following tool versions with different svd's from different vendors:
Python 3.6.3
cmsis-svd 0.4

I also tried different versions of the nRF51_codegen.py file, but always the same problem.

Do you know this issue already? How can we fix this problem?

**Comment by bradjc** [comment]
As you can probably tell, we haven't used that script in a long time. However, I think if you replace

    if register.dim:

with

    if hasattr(register, 'dim'):

you will at least get past that error. I'm not really sure how that script ever worked...

**Comment by Malex92** [comment]
Thanks for the hint bradjc. 

With this litte modification the script works!

**Pull request merged**
