### PR TITLE
Add MPU & SysTick support for NRF52

### PR DESCRIPTION
**Pull request by alevy**
### Pull Request Overview

This pull request adds support for the MPU and SysTick to the NRF52 chip.

This _should_ have been trivial, but ends up requiring a bug fix in the NRF52DK board, and a slight change to the SysTick interface and implementation to deal with a case the NRF52 covers (and other chips may as well).

### SysTick

In some cases, the SysTick calibration is not set by the core. So, in
order to get 10s of ms units, the board/chip must tell us explicitly
what is the clock speed of the SysTick.

This PR, first, creates a real struct for SysTick, similar to the
MPU struct, which contains a tenms field. If the core's tenms register
is 0, we use the struct's field instead. It also adds a constructor that
takes a clock speed and converts it to a tenms.

This change requires changing how SysTick is instantiated in chip crates
since constructors now return a struct instead of a reference. Specifically, if previous `Chip` instances looked like this:

```rust
struct Sam4l {
    systick: &'static cortexm4::systick::SysTick;
}

impl Chip for Sam4l {
    type SysTick = cortexm4::systick::SysTick;
    fn systick(&self) -> &cortexm4::systick::SysTick {
        self.systick
    }
}
```

They should now look like this:

```rust
struct Sam4l {
    systick: cortexm4::systick::SysTick;
}

impl Chip for Sam4l {
    type SysTick = cortexm4::systick::SysTick;
    fn systick(&self) -> &cortexm4::systick::SysTick {
        &self.systick
    }
}
```
Otherwise everything is the same.

For the NRF52, we use a calibration value of 64Mhz for the SysTick since the NRF52's SysTick is
clocked by the CPU clock, which is always 64Mhz.

### MPU

The MPU required fixing a "bug" in the NRF52DK's chip_layout, which was
setting the MIN_MPU_ALIGNMENT to 8 _bytes_ rather than 8K. Other boards
using the NRF52 will also have to ensure this value is set properly.

### Testing Strategy

I ran all the apps in `userland/examples` and `userland/examples/tests` that should work on the NRF52dk. I also created a pair of custom apps that print to the console periodically, but do a busy spin instead of `delay_ms` to verify that the systick is properly switching between processes that don't yield.

### TODO or Help Wanted

~~@shaneleonard & @Vagabond / @JayKickliter should make sure these changes don't cause problems in their off-tree ports. NRF52-based boards should only require changes to `chip_layout.ld`, if any, assuming they weren't somehow relying on the MPU or SysTick not being used.~~

### Documentation Updated

- [x] Kernel: The relevant files in `/docs` have been updated or no updates are required.

### Formatting

- [x] `make formatall` has been run.

### CODE REVIEW

**Comment by alevy** [comment]
It's probably worth taking this opportunity to document systick better. I'll do that, but meanwhile it's a good idea to test these changes if you're maintaining a separate board/chip since I don't expect the implementation to change unless people have comments or suggestions.

**Comment by JayKickliter** [comment]
I loaded your branch on our custom nRF52 board and made the `8 -> 8K` change.

The release build of the kernel runs, but the debug build is panicking on:
```rust
42│
43│ impl kernel::SysTick for SysTick {
44│     fn set_timer(&self, us: u32) {
45│         let tenms = self.tenms();
46├───────> let reload = tenms * us / 10000;
47│
48│         self.regs.value.set(0);
49│         self.regs.reload.set(reload);
50│     }
51│
52│     fn value(&self) -> u32 {
53│         let tenms = self.tenms();
tock/arch/cortex-m4/src/systick.rs
(gdb) info locals
reload = <optimized out>
tenms = 640000
(gdb)
```

Writing to a garbage address in an app (with a release kernel) causes the device to lockup, but the kernel doesn't output anything on the serial console. My current setup doesn't allow me to run release builds under GDB, so I'm not sure what's happening. I can dig in more if necessary.

**Comment by niklasad1** [comment]
I think this should be relatively easy to debug with `checked_mul` and `checked_div` in Rust and do basic printing!

See [https://doc.rust-lang.org/std/primitive.u32.html#method.checked_mul](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_mul)

**Comment by alevy** [comment]
@JayKickliter Thanks! This actually pointed out a real flaw in the computation, not just an issue with debug. Even when wrapping was allowed in release, the result was wrong.

I replaced the computations with divisions instead of multiplies, which sacrifices some precision when the clock speed is not round, but I don't think that's a big deal.

So far this works in my tests, but I still need to set up something a bit more formal to verify this whole PR.

**Comment by alevy** [comment]
I've now tested this pretty rigorously: I ran all of the apps in `userland/examples` and `userland/examples/tests` that should work with the NRF52. I also ran a pair of processes that do some busy waiting to test that the kernel's use of systick actually switches between non-yielding processes. We don't have anything like that in the examples, but it looks like this:

```c
#include <stdio.h>

static void busy(void) {
  volatile int i = 0;
  while (i < 1000000) {
    i++;
  }
}

int main(void) {
  while (1) {
    printf("World\n");
    busy();
  }
}
```
Pending concerns from others, I think this is good to merge.

**Comment by niklasad1** [comment]
Nice nice, MPU is important it will be comforting to have it enabled and also easier to debug user-apps :+1: 

Just to verify two things before merging:
1. Have you executed the ```crash``` and ```MPU_stack_growth``` tests and they went ok?
2. Have you executed the changes on SAM4L (the arch crate is shared for cortex M4) and it went ok?

**Comment by alevy** [comment]
@niklasad1 tested both 1 and 2 (thanks for the reminder to test the SAM4L)

**Comment by alevy** [comment]
@ppannuto how's the documentation I added?

**Comment by alevy** [comment]
Lol, @ppannuto what would I do without you?

**Comment by ppannuto** [comment]
Just finished reading over - love the new documentation ❤️ 

..and I think @bradjc would tell you to turn the spell checker on in your editor :P

**Pull request merged**
