### PR TITLE
Add I2C Slave

### PR DESCRIPTION
**Pull request by bradjc**
Not ready yet, but want to open the issue for any relevant discussion.

### CODE REVIEW

**Comment by bradjc** [comment]
TODO: test if you can have a slave_read slave_write and master_read/write at the same time

**Comment by bradjc** [comment]
Is it possible in Rust to have some sort of combined trait? For example, for I2C it might be nice to have `I2CMaster`, `I2CSlave`, and `I2CMasterSlave` traits. Then a basic driver may only require an I2C driver with the `I2CMaster` trait, and hardware that can only support master mode will work. Another driver may only need slave functionality, and yet another may need both.

What I can think of:

1. Create all three of those traits and implement them all (for platforms that can support it). Then the driver can specify which it wants.
2. Maybe there is a way to say that an object passed to a function must implement two traits (`I2CSlave` and `I2CMaster`)?

**Comment by yuriks** [comment]
iirc the way you specify that is with `<T: Foo + Bar>`, so yes, that's very possible. You can also create a trait that inherits from the two other traits `trait Spam: Foo + Bar`

**Comment by bradjc** [comment]
Ah OK cool. Is there a way to disambiguate functions in traits if they have the same name? So for example, if I have an object that implements the `Spam` trait, and both `Foo` and `Bar` have functions called `enable`, will I get an error, or is there a way to specify which `enable` I mean (`Foo.enable()` or `Bar.enable()`)?

**Comment by yuriks** [comment]
I think you have to manually cast to a specific trait reference (using `as`) before calling the method in those cases.

**Comment by alevy** [comment]
You can also use the explicit syntax: `Foo::enable(myitem)`, since methods are really just syntactic sugar. I personally think this is slightly less bug prone than casting, but either works.

**Comment by bradjc** [comment]
@alevy What are you thoughts on expanding `hil::i2c` to have three traits:
- `I2CMaster`
- `I2CSlave`
- `I2CMasterSlave: I2CMaster + I2CSlave {}`

Then the individual MCU can choose which to implement (for instance nrf51822 does not support slave I2C).

What's trickier is what to do about `MuxI2C`. My best thought so far is to have three options in its constructor:
- `Option<hil::I2CMaster>`
- `Option<hil::I2CSlave>`
- `Option<hil::I2CMasterSlave>`
and then you only set the one that the HW provides you. I guess then MuxI2C panics if you try to use a function that the HW doesn't support.

**Comment by alevy** [comment]
RE: the three traits

Does `I2CMasterSlave` have methods that are not included in `I2CSlave` or `I2CMaster`? If not, I don't think we need it.

RE: `MuxI2C`

Does it ever make sense to use an i2c slave and master from the same client? Would virtualization be exactly the same for slave and master? If no to both, then we should just have separate virtualization implementations (`MuxI2CSlave` and `MuxI2CMaster` or something).

If yes to either, then perhaps keeping a single `MuxI2C` makes sense, in which case the solution is to use an `enum` rather than two/three options:

```rust
enum I2CImpl<'a> {
    Slave(&'a I2CSlave),
    Master(&'a I2CMaster),
}

struct MuxI2C<'a> {
    i2c: I2CImpl<'a>,
    ...
}
```

**Comment by bradjc** [comment]
OK I've finally come up with an I2C slave solution that works. It doesn't use DMA because I could not get DMA to work if the transaction had already started (as in a master had already sent the address byte). Instead it uses interrupts to send each byte.

The slave driver maintains a buffer to read messages into and to write from. If the buffers are not set when a Master sends a message, it clock stretches and calls the upper layers to request a buffer. The upper layer must provide a buffer at that point.

As we discussed with SPI, virtualizing an I2C slave is pretty useless since you can only respond to one I2C address at a time. Therefore I left `virtual_i2c.c` alone. Anyone wishing to use I2C slave should just talk to the `sam4l:i2c:I2CSlave` interface directly. I do have an example of that coming as a part of the signpost project.

I did add the empty trait `I2CMasterSlave`. I tried using `+` to combine them, but then I had to template things and the code became a horrible mess (granted this was when I was trying to update `virtual_i2c`, but I imagine it would be true in general). I agree that having the trait isn't great, but it seems a whole boatload cleaner than having to template everywhere.

**Comment by bradjc** [comment]
There are two more fixes I need to add to the PR at some point:

- chips.rs fix to actually get interrupts
- better interrupt handling for rx bytes in i2c slave

**Comment by alevy** [comment]
@bradjc does "at some point" mean before merging, or is this ready from your perspective?

**Comment by bradjc** [comment]
Before merging for sure.

**Comment by bradjc** [comment]
OK I merged in the fixes.

**Comment by alevy** [comment]
@bradjc what's the status of this? It would be good to merge at least the HIL part as soon as possible, even if the implementation is not yet complete for the I2C slave

**Comment by bradjc** [comment]
The code works, but there is a lingering bug where eventually the slave will hold the I2C lines low and just sit there. It's a little tricky to figure out what conditions make this happen because it usually takes 100s of messages for it to fail. I plan to keep looking into this.

It would be reasonable to merge this and add an issue for that problem. We haven't found any other issues.

**Comment by ppannuto** [comment]
fwiw, I got the smbus controller to enter this state reasonably reliably by
manually toggling the backplane_reset button while running the
backplane_test app -- the module I2C would keep dutifully sending messages
every second, but the smbus was held low.

**Comment by bradjc** [comment]
@ppannuto but that is in master mode, which is an important issue but probably exists despite this PR.

**Pull request merged**
