### PR TITLE
Reformatted all the crates with cargo fmt

### PR DESCRIPTION
**Pull request by Idolf**
The core of my changes were made with this command

```sh
for f in $(find -path ./extern -prune -o -name Cargo.toml -print); do pushd ${f%/Cargo.toml}; cargo fmt; popd; done
```

## Additional changes

- Added `*.bk` to the `.gitignore`
- Added a `rustfmt.toml` to the root.
- Added `#[cfg_attr(rustfmt, rustfmt_skip)]` in a few places where I thought that the original formatting was worth keeping. I might have missed some.
- Removed the comment from the line `mod gpio_dummy` and similar, since there is reason not to test them (and this allowed formatting those files automatically as well)
- Ran `rustfmt` on `src/chips/nrf51822/build.rs` since it was not picked up by `cargo fmt`.
- Deleted `./tests/queue/src/full.rs`, since it was not in use and `./tests/queue/src/main.rs` had the same content.

### CODE REVIEW

**Comment by Idolf** [comment]
This didn't actually fail, Travis just didn't run the osx test for whatever reason.

**Comment by Idolf** [comment]
I have now rebased this. It should be good to merge.

**Comment by ppannuto** [comment]
Could we add something like `cargo fmt -- checkstyle` to Travis so that we avoid style-fix commits in the future?

**Comment by Idolf** [comment]
Yeah, adding something like this to .travis.yml should work:

```sh
find -path ./extern -prune -o -name '*.rs' -exec rustfmt --write-mode=diff {} +
```

Do you want me to add that in this PR as well?

**Comment by ppannuto** [comment]
Feels like a good idea to me, but I'll leave that call up to @alevy

**Comment by alevy** [comment]
I'm in favor

**Comment by Idolf** [comment]
Cool, will do. I will add a bogus commit as well, to see if my travis check is working.

**Comment by Idolf** [comment]
This failed alright, but not because of anything I did. Rather it was because rustup failed.

Perhaps we should transition to using the container+cache feature of travis? That should both make builds faster and more reliable.

**Comment by alevy** [comment]
@idolf that would be nice except that the travis containers don't support a recent enough version of arm-none-eabi. There is a two year old open issue about it... :(

**Comment by ppannuto** [comment]
Can't we deploy our own docker image that just installs it? Maybe via wget
if not apt? I've done that for other things. Can look into that for tock if
you'd like.

**Comment by alevy** [comment]
@ppannuto Seems great, although if not 100% sure it's worth the trouble (so up to you obviously). 

Meanwhile @Idolf  I just manually restarted the build and got `find: `rustfmt': No such file or directory`. Moreover, it looks like uncommenting the test modules in the storm platform's `main.rs` triggers a bunch of unused warnings. Let's add `#[allow(dead_code)]` for now, but maybe the right thing is to wrap each of them in a `#[cfg(test)]` or something such that we can just compile a version with a single cargo feature flag that generates an ELF specifically for testing stuff on the board. Otherwise, recommenting seems like a good temporary solution to get this PR through for now.

**Comment by Idolf** [comment]
@alevy: I added `cargo install rustfmt` and now the build fails as expected (i.e. the find command found my poorly formatted file and complained). I will now remove the bogus commit and it should go through the travis check.

I can add `#[allow(dead_code)]` if you like. I was planning on doing a follow-up PR with fixes this (and the other warnings), since this PR is complicated enough as it is.

**Comment by alevy** [comment]
@idolf OK that's fair. let's leave the PR as is. I'll merge as soon as you squash the breaking commit with a working one. Thanks!

**Comment by Idolf** [comment]
The breaking commit is gone!

**Comment by Idolf** [comment]
Huh. I was wrong. The breaking commit did not break for the reason I thought.

**Comment by Idolf** [comment]
This time it caught it correctly. If it goes through, feel free to merge.

**Comment by Idolf** [comment]
Yep, it went through.

**Comment by alevy** [comment]
Phew!

**Comment by alevy** [comment]
@idolf this actually fails, it turns out, on OS X because the OS X find utility doesn't understand the `-path` argument. For now, I think i'll only run `rustfmt` on Linux, we don't need the duplication anyway

**Pull request merged**
