### PR TITLE
SAM4L I2C: Handle short read_write() correctly

### PR DESCRIPTION
**Pull request by bradjc**
When doing a write_read(), if handling the transition between the two gets delayed and only one byte is to be read, using DMA no longer works since the byte is already in the RHR register. This checks for this specific case and handles it correctly.

Tested by running hail and accel_leds simultaneously.

### CODE REVIEW

**Comment by bradjc** [comment]
In some strange test case that I came up with because of random changes while debugging, this PR worked. Running on this branch, with only the following additional diff (because we don't have fxo sharing yet):

```diff
diff --git a/userland/examples/tests/hail/main.c b/userland/examples/tests/hail/main.c
index 74e5dfca..51114d44 100644
--- a/userland/examples/tests/hail/main.c
+++ b/userland/examples/tests/hail/main.c
@@ -29,13 +29,13 @@ void timer_fired(__attribute__ ((unused)) int arg0,
                  __attribute__ ((unused)) int arg2,
                  __attribute__ ((unused)) void* ud) {
   int temp, humi;
-  uint32_t accel_mag;
+  uint32_t accel_mag = 7;
   int light;
   int a0, a1, a2, a3, a4, a5;
   int d0, d1, d6, d7;
 
   si7021_get_temperature_humidity_sync(&temp, &humi);
-  accel_mag = FXOS8700CQ_read_accel_mag();
+  // accel_mag = FXOS8700CQ_read_accel_mag();
   light = isl29035_read_light_intensity();
 
   // A0-A5
```

and this flashed to hail:
```
$ tockloader list
No serial port specified. Discovering attached serial devices...
Using "/dev/ttyUSB0 - Hail IoT Module - TockOS"
[App 0]
  Name:                  hail
  Total Size in Flash:   8192 bytes

[App 1]
  Name:                  accel-leds
  Total Size in Flash:   4096 bytes
```

I get this error. Ugh.

```
[Hail] Test App!
[App] Accelerometer -> LEDs
[Hail] Samples all sensors and transmits over BLE.
[Hail] Button controls LED.
[Hail Sensor Reading]
  Temperature:  2757 1/100 degrees C
  Humidity:     1462 0.01%
  Light:        62
  Acceleration: 7
  A0:           3025 mV
  A1:           2641 mV
  A2:           2851 mV
  A3:           2528 mV
  A4:           2804 mV
  A5:           2652 mV
  D0:           0
  D1:           0
  D6:           0
  D7:           0

Kernel panic at /home/bradjc/git/tock/chips/sam4l/src/lib.rs:239:
	"Kernel HardFault.
	r0  0x1d1d1d1d
	r1  0x2000163c
	r2  0x1afd7
	r3  0x0
	r12 0x20001538
	lr  0x20001584
	pc  0x2000154c
	prs 0x2000155c
	sp  0x200024c0
	SHCSR 0x0
	CFSR  0x10000
	HSFR  0x40000000
"

---| Fault Status |---
No faults detected.

---| App Status |---
App: hail
 [Yielded]  -  Events Queued: 0  Syscall Count: 108

 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20006000═╪══════════════════════════════════════════╝
             │ ▼ Grant         356 |   1024          
  0x20005E9C ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Unused
  0x20004F94 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ ▲ Heap         1580 |   2048              S
  0x20004968 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ R
             │ ▼ Stack         112 |   2048              A
  0x200048F8 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ M
             │ Unused
  0x20004168 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Data            360 |    360
  0x20004000 ┴───────────────────────────────────────────
             .....
  0x00032000 ┬───────────────────────────────────────────
             │ Unused
  0x00031BB9 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ F
             │ Data            316                       L
  0x00031A7D ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ A
             │ Text           6657                       S
  0x0003007C ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ H
             │ Header          124
  0x00030000 ┴───────────────────────────────────────────

  R0 : 0x000314E7    R6 : 0x00000000
  R1 : 0x00000000    R7 : 0x00000000
  R2 : 0x000314C3    R8 : 0x00000000
  R3 : 0x00000000    R10: 0x00000000
  R4 : 0x20004910    R11: 0x00000000
  R5 : 0x00000000    R12: 0x00000000
  R9 : 0x20004000 (Static Base Register)
  SP : 0x200048F8 (Process Stack Pointer)
  LR : 0x00000000 [0xFFFCFF84 in lst file]
  PC : 0x00000000 [0xFFFCFF84 in lst file]
 YPC : 0x000314D4 [0x8002FAD2 in lst file]

App: accel-leds
 [Yielded]  -  Events Queued: 0  Syscall Count: 15953

 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20008000═╪══════════════════════════════════════════╝
             │ ▼ Grant         316 |   1024          
  0x20007EC4 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Unused
  0x20006EE8 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ ▲ Heap         1528 |   2048              S
  0x200068F0 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ R
             │ ▼ Stack          96 |   2048              A
  0x20006890 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ M
             │ Unused
  0x200060F0 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
             │ Data            240 |    240
  0x20006000 ┴───────────────────────────────────────────
             .....
  0x00033000 ┬───────────────────────────────────────────
             │ Unused
  0x00032EE9 ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ F
             │ Data            207                       L
  0x00032E1A ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ A
             │ Text           3486                       S
  0x0003207C ┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ H
             │ Header          124
  0x00032000 ┴───────────────────────────────────────────

  R0 : 0x00000000    R6 : 0x200068D4
  R1 : 0x00032B8F    R7 : 0x200068D0
  R2 : 0x200060D0    R8 : 0x200068CC
  R3 : 0x00032C01    R10: 0x00000000
  R4 : 0x200060DC    R11: 0x00000000
  R5 : 0x00000000    R12: 0x00032C01
  R9 : 0x20006000 (Static Base Register)
  SP : 0x20006890 (Process Stack Pointer)
  LR : 0x00032BA7 [0x80000B2A in lst file]
  PC : 0x00000382 [0xFFFCE306 in lst file]
 YPC : 0x00032B7C [0x80031DDE in lst file]
```

CFSR of 0x10000 means the CPU tried to execute an undefined instruction. Which would make sense if the PC is actually at 0x2000154c.

So I guess I keep searching...

**Comment by bradjc** [comment]
But with this diff on top of the branch:

```diff
diff --git a/boards/hail/src/main.rs b/boards/hail/src/main.rs
index b9fb9c96..b60baf94 100644
--- a/boards/hail/src/main.rs
+++ b/boards/hail/src/main.rs
@@ -354,6 +354,10 @@ pub unsafe fn reset_handler() {
     sam4l::gpio::PA[17].clear();
     sam4l::gpio::PA[17].set();
 
+
+    sam4l::gpio::PB[14].enable();
+    sam4l::gpio::PB[14].enable_output();
+
     hail.console.initialize();
index 422ddf90..07143dc5 100644
--- a/chips/sam4l/src/i2c.rs
+++ b/chips/sam4l/src/i2c.rs
@@ -21,6 +21,7 @@ use kernel::common::volatile_cell::VolatileCell;
 use kernel::hil;
 use nvic;
 use pm;
+use gpio;
 
 // Listing of all registers related to the TWIM peripheral.
 // Section 27.9 of the datasheet
@@ -309,6 +310,9 @@ impl I2CHw {
                                 // Save the already read byte.
                                 buf[0] = read_volatile(&mut regs.receive_holding) as u8;
                                 client.command_complete(buf, err);
+                                // unsafe {
+                                //     gpio::PB[14].toggle();
+                                // }
                             });
                         });
                     });
diff --git a/userland/examples/tests/hail/main.c b/userland/examples/tests/hail/main.c
index 74e5dfca..f026cb56 100644
--- a/userland/examples/tests/hail/main.c
+++ b/userland/examples/tests/hail/main.c
@@ -29,13 +29,13 @@ void timer_fired(__attribute__ ((unused)) int arg0,
                  __attribute__ ((unused)) int arg2,
                  __attribute__ ((unused)) void* ud) {
   int temp, humi;
-  uint32_t accel_mag;
+  uint32_t accel_mag = 7;
   int light;
   int a0, a1, a2, a3, a4, a5;
-  int d0, d1, d6, d7;
+  int d0=9, d1, d6, d7;
 
   si7021_get_temperature_humidity_sync(&temp, &humi);
-  accel_mag = FXOS8700CQ_read_accel_mag();
+  // accel_mag = FXOS8700CQ_read_accel_mag();
   light = isl29035_read_light_intensity();
 
   // A0-A5
@@ -47,7 +47,7 @@ void timer_fired(__attribute__ ((unused)) int arg0,
   a5 = (adc_read_single_sample(6) * 3300) / 4095;
 
   // D0, D1, D6, D7
-  d0 = gpio_read(0);
+  // d0 = gpio_read(0);
   d1 = gpio_read(1);
   d6 = gpio_read(2);
   d7 = gpio_read(3);
@@ -87,7 +87,7 @@ int main() {
   adc_initialize();
 
   // Setup D0, D1, D6, D7
-  gpio_enable_input(0, PullDown); // D0
+  // gpio_enable_input(0, PullDown); // D0
   gpio_enable_input(1, PullDown); // D1
   gpio_enable_input(2, PullDown); // D6
   gpio_enable_input(3, PullDown); // D7
```

Things work as expected.

I'm kinda at a loss on this one.

**Comment by bradjc** [comment]
Could this be a kernel stack problem too?

**Comment by bradjc** [comment]
I tried this again (rebased on master with the above diff to the hail test app) and the I2C seems to work, but at some point the app does a couple of the `printf()`s but then stops. The application seems to get stuck in the `printf()` until its stack grows too large and it crashes. I can't really tell where its getting stuck.

The sensor readings keep going, however. The I2C bus is in almost constant use. It might be good to merge this since it does address the problem I was having, and we can keep tracking down other bugs going forward.

**Comment by alevy** [comment]
Why would this never be a problem for, say, a two-byte packet? Is there a solution that just gets the interrupt to be asserted properly for the one-byte case instead? For example, by using the DMA interrupt instead of the TWIM interrupt?

**Comment by bradjc** [comment]
Two bytes are fine, because there is only a single byte buffer so the I2C hardware will have to delay until the first byte is read, and this allows for enough time for DMA to be setup.

I tried getting more interrupts out of the TWIM peripheral, but that lead to all sorts of weird behavior. I tried using the DMA interrupt, but since the DMA never actually seems to run, that interrupt didn't work either.

I tried not using the "next transfer" command in this case to ensure there would be enough time to setup DMA, and that didn't work either.

My impression from this and I2C slave mode is that the TWIM module is super flaky and not well designed.

**Pull request merged**
