### PR TITLE
Bump rustc *and* rustfmt nightly

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

This updates to latest rustc and rustfmt. This should address the problems from #718, but we'll have to keep updating rustfmt as we update rustc (probably not an unreasonable notion).

### Testing Strategy

Running most applications on a hail.

### TODO or Help Wanted

The potentially risky bit is dd0e9cc9 -- as outlined in that commit, it changes the MMIO structures from `repr(C,packed)` to just `repr(C)`. By my reading of https://doc.rust-lang.org/beta/nomicon/other-reprs.html, this should be safe to do. Indeed, a few things (SAM4L TRNG and some USB) already didn't have packed. However, it would be good to test that this doesn't break things for folks.

Additionally, bumping rustfmt results in some pretty significant code churn, so I'd like to give the out-of-tree folks the chance to holler if it's going to make their lives awful for any reason.

### Documentation Updated

- [X] Kernel: The relevant files in `/docs` have been updated or no updates are required.
- [X] Userland: The application README has been added, updated, or no updates are required.

### Formatting

- [X] `make formatall` has been run (and then some :P)

### CODE REVIEW

**Comment by ppannuto** [comment]
Okay, I think this should be good to go.

There's some urgency to merge this now. With the newest version of rustup (2018-01-04, [which new travis builds already dutifully installing](https://travis-ci.org/helena-project/tock/builds/326845989#L495)), components won't leak across installed versions (this is actually a good thing, I think this should also fix the annoying habit of re-building std every time you change versions), however it breaks the old approach we'd used to pin rustfmt version -- it's why #721's build failed.

**Comment by bradjc** [comment]
Why update rustfmt? It hasn't hit 1.0, and I don't think we want to have the code keep reformatting every month or two.

**Comment by ppannuto** [comment]
Two conflating things as rustfmt matures:

 - From #718, support tooling is integrating formatting. Pinning our own version will get harder with time, particularly since:
 - Rustfmt is now a "component" that ties into `rustup`, and will follow rustc version changes. With rustup >= 1.9.0, I don't think we can install rustfmt < 0.2 (yes.. they reset their numbering a little while ago, so current (v0.3.4) is newer than what we'd pegged (v0.7.1)

Note that with the old approach #721 travis failed because it couldn't run rustfmt. (While we could peg a rustup version back as well to fix that, it would break once we bump rustc's anyway)

We don't necessarily have to bump rustfmt with every bump of rustc, but rustfmt v0.7.1 is ~1 year old today, and that's now too old to work.

**Comment by bradjc** [comment]
How is travis getting such a new version of rustup?

```
curl https://sh.rustup.rs -sSf | head -n 30
```

Shows version 1.0.0 from February. Do we expect users to have super recent versions?

I'm really just hesitant to refactor all of the code quickly if there is a quick and easy way to not to...particularly because rustfmt will likely change and we'll have to do it again. With branches and outstanding pull requests and out-of-tree stuff it can get messy to have so much of the main repo change.

**Comment by ppannuto** [comment]
That's "rustup-init" version 1.0.0
`rustup-init 1.0.0 (408ed84 2017-02-11)`

[Rustup is on 1.9.0](https://github.com/rust-lang-nursery/rustup.rs/commit/a918ea0d617983e0e9c97b7f65eafa3484cf9d56)

**Comment by bradjc** [comment]
OK it seems that rust is forcing our hand here. But we should be able to pin the version of rustfmt after this so that we don't have regular churn until rustfmt stabilizes?

**Comment by ppannuto** [comment]
I think so yeah, we should be able to hang out at 0.3.4 until something else major changes

**Pull request merged**
