### PR TITLE
Clarified which versions of programs are required

### PR DESCRIPTION
**Pull request by brghena**

### CODE REVIEW

**Comment by brghena** [comment]
Looking for a once over from anyone else and a version requirement for `openocd`

**Comment by bradjc** [comment]
Why not just use `pip3 install tockloader --upgrade`? That way even if we don't change the version in all of the readmes right away, new people will get the new version.

**Comment by brghena** [comment]
Well if we specified `--upgrade` and you release a `0.6.0` that isn't compatible (because there's a PR still in progress in Tock, for instance) someone might have the wrong version.

Basically, I think `tockloader` should be handled exactly the same as `rustfmt` or `rustc`. We do control it, but it seems better to me to specify the exact version a user should be on.

If you think minor versions with bugfixes will come out that you want to allow users to transparently update to but not require it, we could change to `pip3 install tockloader>0.5.0,<0.5.99` ([apparently .99 is the way to do this](https://groups.google.com/forum/#!msg/python-virtualenv/DvG1InRGdR0/14b9CISO2AcJ))

**Comment by alevy** [comment]
Openocd 0.8.0 seems right (that's the version they added SAM4L support)

**Comment by brghena** [comment]
Updated. I double checked that apt installs the right version on ubuntu (`0.9.0`) and brew installs the right version on MacOS (`0.10.0`).

**Pull request merged**
