### PR TITLE
Userland: add PIC libm

### PR DESCRIPTION
**Pull request by bradjc**
Original solution of -lm does NOT work as it was not including a PIC version of libm.

This PR needs to also edit a README to explain where `libm.a` came from. @ppannuto 

Also it would be great if @ppannuto would also update the commit author to match his github email.

### CODE REVIEW

**Comment by alevy** [comment]
Oh yes, this is highly correct. What do you want the README to say? Like, how to recompile libm?

**Comment by bradjc** [comment]
Yeah where this magic libm.a file came from.

**Comment by ppannuto** [comment]
This PR should also cherry-pick https://github.com/helena-project/tock/pull/176/commits/27a01f5fd401536b3dcba011b7ea6f1167ffa6a2 to have an example app that builds with PIC libm

I have some changes floating around somewhere with the cxx stuff that cleans up the build of newlib, I'll find those

**Comment by bradjc** [comment]
I'm not entirely convinced we need an example of using `math.h` which is pretty standard, but I think `math_blink` is confusing and not good for new users. I could see adding a math app to tests, but I'm still not sure about the value of that.

**Comment by ppannuto** [comment]
I guess what I really want is an app sitting around that uses a math function so that linking libm is tested, doesn't have to be its own app.

**Comment by alevy** [comment]
@ppannuto the accelerometer test app in userland/examples/test needs to have a `sqrt` added to the result which I believe requires a correctly compiled `libm`

**Comment by ppannuto** [comment]
Perfect.

**Pull request merged**
