### PR TITLE
Remove inline(never) upgrade Rust version

### PR DESCRIPTION
**Pull request by alevy**
I was just super wrong. I just didn't upgrade to the right Rust
version...

@niklasad1 can you approve when you're satisfied that it actually works this time?

### CODE REVIEW

**Comment by brghena** [comment]
This also needs to update `doc/Getting_Started.md`, `.travis.yml`, and `Vagrantfile`

**Comment by alevy** [comment]
@brghena not sure where in .travis.yml, but updated Getting_Started and Vagrantfile

**Comment by brghena** [comment]
Does not this line need to change? https://github.com/helena-project/tock/blob/master/.travis.yml#L16

**Comment by niklasad1** [comment]
It works fine now, you're good to go @alevy

**Pull request merged**
