### PR TITLE
Add Accelerometer to LEDs App

### PR DESCRIPTION
**Pull request by bradjc**
This is a pretty good test app for the accelerometer because as you hold the board in different orientations, different LEDs come on.

It also adds a `sync` function for getting acceleration data.

### CODE REVIEW

**Comment by brghena** [comment]
This is blocked on issue #208

**Comment by bradjc** [comment]
Well it compiles, works, and runs, it just doesn't have quite the intended visual effect.

**Comment by alevy** [comment]
#208 should Should be fixed by #212

**Comment by alevy** [comment]
Just tested with a merge of both PRs and it works! (Pretty cool app... I spent like 2 minutes just moving my board around and staring at the LED change).

**Pull request merged**
