### PR TITLE
Use valid BLE advertisement address for NRF5X

### LINKED ISSUE #659: [nRF5X Bluetooth Low Energy] Doesn't work on iPhone
Hi,

As noticed in [#649](https://github.com/helena-project/tock/pull/649) the Bluetooth Low Energy advertisements can't be found on iPhone using the app  ```nRF Connect``` and need to be fixed!

Currently, it works on Android (at least on Samsung S6).
It need to be investigated further!!

### PR DESCRIPTION
**Pull request by niklasad1**
### Pull Request Overview

This pull request fixes so that NRF5X is using valid Bluetooth Low Energy address during advertising to appear on both Android and iOS.

Also closes #659 

### Testing Strategy
```ble advertising app``` was tested on both nRF51-DK and nRF52-DK

### Documentation Updated

~~- [ ] Kernel: The relevant files in `/docs` have been updated or no updates are required.~~
~~- [ ] Userland: The application README has been added, updated, or no updates are required.~~

### Formatting

- [x] `make formatall` has been run.

### CODE REVIEW

**Comment by alevy** [comment]
1. Could you explain why this fixes the problem?

2. It seems like the _real_ issue is not that the default payload is all zeros (which is reasonable), but that the app we're running `ble_advertising`) never actually sets the address (by calling `allow(BLE_DRIVER, 0x30, address)` or whatever).

3. Will the in progress PR #661 obviate this bug? Because that driver will replace the one currently in use, and that driver actually does set the BLE addresses to something meaningful, right?

**Comment by niklasad1** [comment]
1. It configures the default advertisement address to f0 0 0 0 0 f0 

2. It is a dirty-quick hack because there are no user-space function to configure the advertisement address. If I recall correctly you don't like and I removed it :smile: 

3. (#661)[https://github.com/helena-project/tock/pull/661] fixes this completely where the kernel is responsible to allocate advertisement addresses

**Comment by alevy** [comment]
Ok, ubderstood, thanks.

I get this is a temporary hack, which is fine. Would it be much more difficult to either add the user level functions or at set the address during ble_advertsement driver initialization maybe, instead hard coding it in the low level driver (where it may inadvertently stay?)

**Comment by niklasad1** [comment]
User-space is probably the easiest, but I don’t have access at moment!

**Pull request merged**
