### PR TITLE
rf233: Implement start() and stop()

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request adds support for putting the RF233 in sleep mode. All changes taken from #692 and moved to separate PR for easier reviewing.

### Testing Strategy

See #692

### Documentation Updated

- [x] Kernel: The relevant files in `/docs` have been updated or no updates are required.
- [x] Userland: The application README has been added, updated, or no updates are required.

### Formatting

- [x] `make formatall` has been run.

### CODE REVIEW

**Comment by alevy** [comment]
This seems totally good to me. I'm happy with this if @ptcrews, @jlwatson @bbbert et al are willing to deal with bugs that may inadvertently be introduced to their 6lowpan-related code.

**Comment by ppannuto** [comment]
@ptcrews @jlwatson @bbbert any objections to merging this?

**Comment by jlwatson** [comment]
@ppannuto apologies for the delay. I want to quickly try out the `sixlowpan_dummy` tests this afternoon before merging, but other than that, @alevy I'm happy to deal with any bugs that pop up in the future.

**Comment by jlwatson** [comment]
Ok, should be good to go!

**Pull request merged**
