### PR TITLE
Code Review process document & establishing a "core team"

### PR DESCRIPTION
**Pull request by phil-levis**
### Pull Request Overview

Adds CodeReview.md, which describes our code process.

### Testing Strategy

Through trial, error, and arguments on the weekyl call.

### TODO or Help Wanted

Let's try following our process! So vote!

### Documentation Updated

- [ x] Kernel: The relevant files in `/docs` have been updated or no updates are required.
- [ x] Userland: The application README has been added, updated, or no updates are required.

### Formatting

- [x ] `make formatall` has been run.

---

[Rendered](https://github.com/helena-project/tock/blob/code-review-doc/doc/CodeReview.md)

### CODE REVIEW

**Comment by brghena** [comment]
I updated the Code Review document to add more info about the review process and restarting reviews. I also cleaned up some formatting. Feel free to back out the commit if you disagree with anything.

**Comment by niklasad1** [comment]
This is great but I have two comments:
1. What is the ```standardized testing procedure``` in Tock?
2. What is your thoughts about having releases that matches Rust`s (every 6th week) ? But then we need date or version number as tag instead of month and year!

**Comment by alevy** [comment]
@niklasad1 

> What is the standardized testing procedure in Tock?

What are you referring to? There is mention of a "standardized process for reviewing pull requests", which refers to the process in this PR.

> What is your thoughts about having releases that matches Rust`s (every 6th week) ? But then we need date or version number as tag instead of month and year!

I don't think we want to commit to such a specific cycle just yet. Two months is vague enough that we can nudge it one way or the other to try and fit features into a particular release.

**Comment by alevy** [comment]
I think we should remove the TRD header though, I'm not sure it's doing any useful work here.

**Comment by niklasad1** [comment]
@alevy 

> What are you referring to? There is mention of a "standardized process for reviewing pull requests", which refers to the process in this PR.

I refer to the following: 
*One week before the intended release date, all new pull requests are put on hold, and everyone uses/tests the software using the ```established testing process```*

> I don't think we want to commit to such a specific cycle just yet. Two months is vague enough that we can nudge it one way or the other to try and fit features into a particular release.

Sure 👍

**Comment by alevy** [comment]
> I refer to the following: [...]

Ah, I see. That's... to be determined still :), but I think the intention is that over time we establish a more rigorous and consistent set of tests.

**Pull request merged**
