### PR TITLE
Update .gitignore to include *~ and *.swp

### PR DESCRIPTION
**Pull request by hudson-ayers**
### Pull Request Overview

This pull request updates .gitgnore to include *~ and *.swp files

### CODE REVIEW

**Comment by ppannuto** [comment]
Hah, probably a good idea :)

Maybe update to include all the swap files from the github vim template: https://github.com/github/gitignore/blob/master/Global/Vim.gitignore ?

**Comment by alevy** [comment]
I'm conflicted about this (I will not block it though just my two cents)

My feeling is that environment specific ignores should go in a user's .git/info/exclude file rather than the checked in .gitignore

**Comment by ppannuto** [comment]
I’d say in principle you may be right, in practice we should aim for the
user-friendly approach — I’ve been at this for a long time and don’t have a
user git exclude file (though really should..).

We never want swap files in the repo, this is one form of expressing that
policy.

**Comment by brghena** [comment]
My belief has always been that adding things to .gitignore is harmless. Clearly we're not going to list every little thing in it, but we can at least stop problems that we are repeatedly seeing. Adding swap files by mistake has happened several times before, and will likely keep occurring. (It happened to me once too)

**Comment by alevy** [comment]
Okay okay :)

**Pull request merged**
