### PR TITLE
doc: sync syscalls with the source

### PR DESCRIPTION
**Pull request by bradjc**
We really really really really really really really really need to be more careful about this before merging pull requests.

### CODE REVIEW

**Comment by ppannuto** [comment]
It looks like that return code isn't actually in the kernel anywhere and is only used one place in userland. Do we actually want to add this? Maybe we should pull that error code out of userland?

**Comment by bradjc** [comment]
I mean its in the source now, and needs to be documented. If we want to change our list of error codes, that's a different issue.

**Comment by ppannuto** [comment]
I'm arguing that instead of documenting the one use, you remove the one use, then it's not "in our source now" and doesn't "need to be documented"

**Comment by bradjc** [comment]
I would think that evaluating which error codes we want is difficult and will take time, and until then, we should establish a policy of having our documentation match our code. And when we do identify discrepancies they should get fixed rapidly.

**Comment by alevy** [comment]
I agree with Pat that it's odd that it's only used in one place but agree with Brad that meanwhile documenting it makes sense.

**Pull request merged**
