### PR TITLE
Corrode nrf51

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

Using https://github.com/jameysharp/corrode, automatically convert the
old crt1.c to Rust. In contrast to #369, which sought to update this
file to newer Tock conventions, this is a blind translation, but should
hopefully unblock #367.

### Testing Strategy

Tested with simple apps on a nrf51dk, but not thoroughly stressed.

### TODO or Help Wanted

Testing on the 51 and 52 to make sure I didn't break anything.

### Documentation Updated

- [x] Kernel: ~~The relevant files in `/docs` have been updated or~~ no updates are required.
- [x] Userland: ~~The application README has been added, updated, or~~ no updates are required.

### Formatting

- [x] `make formatall` has been run.

### CODE REVIEW

**Comment by alevy** [comment]
@ppannuto you tested this on the NRF51? I don't have an NRF52 handy but maybe @niklasad1 or @JayKickliter can help just sanity check this?

**Comment by ppannuto** [comment]
Yeah it’s only blink-tested on the 51 at the moment. I can do more robust
51 testing tomorrow, but I’d appreciate someone with a 52 giving it a
sanity check

**Comment by niklasad1** [comment]
I can check late tonight or in the weekend!

**Comment by niklasad1** [comment]
nrf52 tests

- [X] LEDs
- [ ] Bluetooth Low Energy
(this is because of mismatch of syscall numbers in Tock 1.0, included in [#623](https://github.com/helena-project/tock/pull/623) )
- [x] Buttons
- [x] RNG
- [ ] Sensors 
- [ ] AES
- [ ] printf_long
```bash
TOCK_DEBUG(0): src/main.rs:343: Initialization complete. Enterin
```
Sensors, AES, printf_long hangs after loading the userapps we had this problem way back but if remember correctly @alevy debugged this and found some problem with alignment on userapps.
However, I have not debugged this and it need to be solved.

**Comment by niklasad1** [comment]
@ppannuto how did this work for you? :small_airplane: 

The binaries seem to have no instructions..... 
See info about my settings below:

``` bash 
➜  release git:(corrode-nrf51) ✗ git branch                
* corrode-nrf51
➜  release git:(corrode-nrf51) ✗ git rev-parse HEAD
3153cba599522eaa1eaf7f7b98b7b0ea12b95ab2
➜  release git:(corrode-nrf51) ✗ rustc -V
rustc 1.22.0-nightly (a47c9f870 2017-10-11)
➜  release git:(corrode-nrf51) ✗ xargo -V  
xargo 0.3.9
cargo 0.23.0-nightly (e447ac7e9 2017-09-27)
```


**nRF52**
``` bash
$ arm-none-eabi-objdump -d nrf52dk.elf 
nrf52dk.elf:     file format elf32-littlearm
$ arm-none-eabi-size nrf52dk.elf 
   text	   data	    bss	    dec	    hex	filename
      0	      0	   4096	   4096	   1000	nrf52dk.elf
```
**nRF51**
``` bash
$ arm-none-eabi-objdump -d nrf51dk.elf 
nrf51dk.elf:     file format elf32-littlearm
$ arm-none-eabi-size nrf51dk.elf 
   text	   data	    bss	    dec	    hex	filename
      0	      0	   4096	   4096	   1000	nrf51dk.elf
```

**Comment by ppannuto** [comment]
Umm.. I will check tomorrow, I wrote this sitting in a lecture hall, and
blink still blinked — but now I’m wondering if that’s because flash didn’t
flash or something more of that nature.

Your zero size triggered the thought that I don’t think I put the vector
table into a section and I highly doubt corrode kept that gcc attribute.

Sorry for the false start here..

**Comment by alevy** [comment]
94daf0bbf770e4b3 should fix the issues with `sensors` and other apps nrf5x on master. Please rebase before testing again. It was a subtle but bad bug. My bad...

**Comment by ppannuto** [comment]
Okay, this is revised. My suspicion was correct, the problems stemmed from the missing vectors section specifier, which is the only thing kept by the linker, so with no symbols reachable rust helpfully eliminated the entire kernel, and made a 0 byte binary - which the build system happily flashed "successfully" - which is why everything "still worked". Sorry I didn't notice on the first pass, I was trying corrode during some talks and was pleasantly surprised when things "just worked".

**Testing**

|                 | 51 | 52 |
|-----------------|----|----|
| Blink           | X  | *  |
| Buttons         | X  | *  |
| Sensors         | *  | *  |
| printf_long     | X  | X  |
| AES             | X  | X  |
| ble_advertising | :( | :( |

There's some things that don't feel quite right, but they have identical behavior with this PR and master:

 - *blink*: [52-only] Only LEDs 1 and 3 actually cycle on and off, however the pattern implies that the board thinks it has 4 LEDs
 - *buttons*: [52-only] Only Button1 works to control LED1
 - *sensors*: The app loads, prints its welcome message, then prints a blank line every second; presumably because there are no sensors?
 - *ble*: Not debugged any further than "my phone doesn't see it"

**Comment by niklasad1** [comment]
All right, good work @ppannuto :+1: 

I can help with `ble_advertising debugging` most likely that something in the my latest PR broke something.

As far I can tell this is PR is good to go but I want to test it first!

**Pull request merged**
